insert into public.places (
  id, category, image_url, map_link,
  title_en, desc_en, title_el, desc_el, title_ru, desc_ru, title_zh, desc_zh,
  is_best_of_month, lat, lng, town
) values
(
  'edro',
  'views',
  'images/edro.jpg',
  'https://maps.google.com/?q=34.8729743,32.3407762',
  $edroen_t$Edro III Shipwreck$edroen_t$,
  $edroen$Located near the stunning Sea Caves of Peyia, the Edro III Shipwreck is a mesmerizing modern landmark. This cargo ship, which ran aground in 2011, rests dramatically against the rocky coastline, offering one of the most spectacular sunset views on the island.$edroen$,
  $edroel_t$Ναυάγιο Edro III$edroel_t$,
  $edroel$Κοντά στις εντυπωσιακές Θαλασσινές Σπηλιές της Πέγειας, το Ναυάγιο Edro III αποτελεί ένα μαγευτικό σύγχρονο αξιοθέατο. Το φορτηγό πλοίο, που προσάραξε το 2011, αναπαύεται επιβλητικά πάνω στα βράχια, προσφέροντας ίσως το πιο θεαματικό ηλιοβασίλεμα στο νησί.$edroel$,
  $edroru_t$Кораблекрушение Edro III$edroru_t$,
  $edroru$Кораблекрушение Edro III, расположенное недалеко от потрясающих морских пещер Пейи, является завораживающей современной достопримечательностью. Грузовое судно, севшее на мель в 2011 году, живописно покоится на скалистом побережье, предлагая одни из самых впечатляющих видов на закат.$edroru$,
  $edrozh_t$埃德罗三号沉船 (Edro III)$edrozh_t$,
  $edrozh$埃德罗三号沉船 (Edro III Shipwreck) 位于佩亚 (Peyia) 令人惊叹的海蚀洞附近，是一个令人着迷的现代地标。这艘在 2011 年搁浅的货船极具戏剧性地停靠在岩石海岸线上，提供岛上最壮观的日落景色之一。$edrozh$,
  false,
  34.8729743,
  32.3407762,
  'paphos'
),
(
  'petra',
  'views',
  'images/petra-tou-romiou.jpg',
  'https://maps.google.com/?q=34.6649667,32.6272',
  $petraen_t$Petra tou Romiou$petraen_t$,
  $petraen$Also known as Aphrodite's Rock, this stunning geological formation off the coast of Paphos is the legendary birthplace of the Greek goddess of love. It provides breathtaking sunsets and crystal-clear waters, making it an iconic, must-visit viewpoint.$petraen$,
  $petrael_t$Πέτρα του Ρωμιού (Βράχος της Αφροδίτης)$petrael_t$,
  $petrael$Γνωστή και ως ο Βράχος της Αφροδίτης, αυτός ο εκπληκτικός γεωλογικός σχηματισμός είναι η θρυλική γενέτειρα της θεάς του έρωτα. Προσφέρει μαγευτικά ηλιοβασιλέματα και κρυστάλλινα νερά, αποτελώντας ένα εμβληματικό σημείο θέας που πρέπει να επισκεφθείτε.$petrael$,
  $petraru_t$Скала Афродиты (Петра ту Ромиу)$petraru_t$,
  $petraru$Это потрясающее геологическое образование, также известное как Скала Афродиты, является легендарным местом рождения греческой богини любви. Отсюда открываются захватывающие закаты и кристально чистые воды, что делает его знаковым местом для посещения.$petraru$,
  $petrazh_t$佩特拉·图·罗米乌 (阿佛洛狄忒之岩)$petrazh_t$,
  $petrazh$佩特拉·图·罗米乌 (Petra tou Romiou) 又称阿佛洛狄忒之岩，是帕福斯海岸外一处令人惊叹的地质奇观，相传是希腊爱神的诞生地。这里提供令人惊叹的日落和清澈见底的海水，是一个标志性的必游观景点。$petrazh$,
  false,
  34.6649667,
  32.6272,
  'paphos'
),
(
  'paphoscastleview',
  'views',
  'images/paphos-castle.jpg',
  'https://maps.google.com/?q=34.7536347,32.4069529',
  $paphoscastleviewen_t$Paphos Castle$paphoscastleviewen_t$,
  $paphoscastleviewen$Guarding the picturesque harbor of Kato Paphos, this medieval stone fortress stands as a proud symbol of the city. Climbing to the top offers stunning, unobstructed panoramic views of the Mediterranean Sea and the vibrant marina.$paphoscastleviewen$,
  $paphoscastleviewel_t$Κάστρο της Πάφου$paphoscastleviewel_t$,
  $paphoscastleviewel$Φρουρός στο γραφικό λιμανάκι της Κάτω Πάφου, αυτό το μεσαιωνικό πέτρινο φρούριο στέκεται ως σύμβολο της πόλης. Η ανάβαση στην κορυφή του προσφέρει εκπληκτική, ανεμπόδιστη πανοραμική θέα στη Μεσόγειο Θάλασσα και τη ζωντανή μαρίνα.$paphoscastleviewel$,
  $paphoscastleviewru_t$Замок Пафоса$paphoscastleviewru_t$,
  $paphoscastleviewru$Эта средневековая каменная крепость, охраняющая живописную гавань Като Пафоса, гордо возвышается как символ города. Подъем на вершину предлагает потрясающий, беспрепятственный панорамный вид на Средиземное море и оживленную пристань.$paphoscastleviewru$,
  $paphoscastleviewzh_t$帕福斯城堡 (Paphos Castle)$paphoscastleviewzh_t$,
  $paphoscastleviewzh$这座中世纪的石头要塞守护着风景如画的加藤帕福斯 (Kato Paphos) 港口，是这座城市的骄傲象征。登上顶端，可以一览无余地欣赏地中海和充满活力的码头的壮丽全景。$paphoscastleviewzh$,
  false,
  34.7536347,
  32.4069529,
  'paphos'
),
(
  'capegreco',
  'views',
  'images/cape-greco.jpg',
  'https://maps.google.com/?q=34.9568,34.088',
  $capegrecoen_t$Cape Greco Sea Caves$capegrecoen_t$,
  $capegrecoen$Located at the southeastern tip of Cyprus, Cape Greco is renowned for its dramatic sea caves and rugged cliffs. It is the ultimate viewpoint for taking in the breathtaking panoramic vistas of the crystal-clear turquoise waters and dramatic coastal sunsets.$capegrecoen$,
  $capegrecoel_t$Θαλασσινές Σπηλιές Κάβο Γκρέκο$capegrecoel_t$,
  $capegrecoel$Στο νοτιοανατολικό άκρο της Κύπρου, το Κάβο Γκρέκο φημίζεται για τις εντυπωσιακές θαλασσινές σπηλιές και τους απόκρημνους βράχους του. Είναι το απόλυτο σημείο για να θαυμάσετε την εκπληκτική πανοραμική θέα στα κρυστάλλινα γαλαζοπράσινα νερά και τα δραματικά ηλιοβασιλέματα.$capegrecoel$,
  $capegrecoru_t$Морские пещеры Каво Греко$capegrecoru_t$,
  $capegrecoru$Мыс Греко, расположенный на юго-восточной оконечности Кипра, известен своими живописными морскими пещерами и скалистыми утесами. Это идеальная смотровая площадка, откуда открывается захватывающий панорамный вид на кристально чистую бирюзовую воду и потрясающие прибрежные закаты.$capegrecoru$,
  $capegrecozh_t$格雷科角海蚀洞 (Cape Greco)$capegrecozh_t$,
  $capegrecozh$格雷科角 (Cape Greco) 位于塞浦路斯东南部边缘，以其引人入胜的海蚀洞和崎岖的悬崖而闻名。这里是欣赏清澈见底的绿松石般海水和壮丽海岸日落全景的终极观景点。$capegrecozh$,
  false,
  34.9568,
  34.088,
  'famagusta'
),
(
  'lovebridge',
  'views',
  'images/lovebridge.jpg',
  'https://maps.google.com/?q=34.98722,34.07361',
  $lovebridgeen_t$Love Bridge$lovebridgeen_t$,
  $lovebridgeen$A masterpiece of nature, this natural rocky arch extending into the crystal-clear sea is one of Ayia Napa's most photographed spots. It offers a romantic and incredibly scenic viewpoint, perfect for capturing the essence of the Mediterranean coast.$lovebridgeen$,
  $lovebridgeel_t$Γέφυρα των Ερωτευμένων$lovebridgeel_t$,
  $lovebridgeel$Ένα αριστούργημα της φύσης, αυτή η φυσική βραχώδης αψίδα που εκτείνεται μέσα στην κρυστάλλινη θάλασσα είναι από τα πιο πολυφωτογραφημένα σημεία της Αγίας Νάπας. Προσφέρει μια ρομαντική και απίστευτα γραφική θέα, ιδανική για να απαθανατίσετε τη μαγεία της Μεσογείου.$lovebridgeel$,
  $lovebridgeru_t$Мост влюбленных (Love Bridge)$lovebridgeru_t$,
  $lovebridgeru$Этот природный скалистый свод, уходящий в кристально чистое море, является шедевром природы и одним из самых фотографируемых мест Айя-Напы. Отсюда открывается романтичный и невероятно живописный вид, идеально передающий суть средиземноморского побережья.$lovebridgeru$,
  $lovebridgezh_t$情人桥 (Love Bridge)$lovebridgezh_t$,
  $lovebridgezh$这座延伸至清澈海水中的天然岩石拱门是大自然的杰作，也是圣纳帕出镜率最高的地标之一。它提供了一个浪漫且风景如画的视角，非常适合捕捉地中海海岸的精髓。$lovebridgezh$,
  false,
  34.98722,
  34.07361,
  'famagusta'
),
(
  'sculpturepark',
  'views',
  'images/sculpturepark.jpg',
  'https://maps.google.com/?q=34.9878,34.0675',
  $sculptureparken_t$Sculpture Park$sculptureparken_t$,
  $sculptureparken$Situated on a hill overlooking the sea, this open-air museum blends art with nature. Strolling through the park provides not only a cultural experience but also elevated, sweeping panoramic views of the endless blue sea below.$sculptureparken$,
  $sculptureparkel_t$Πάρκο Γλυπτικής Αγίας Νάπας$sculptureparkel_t$,
  $sculptureparkel$Χτισμένο σε έναν λόφο με θέα τη θάλασσα, αυτό το υπαίθριο μουσείο συνδυάζει την τέχνη με τη φύση. Μια βόλτα στο πάρκο δεν προσφέρει μόνο μια πολιτιστική εμπειρία, αλλά και πανοραμική, ανεμπόδιστη θέα στο απέραντο γαλάζιο.$sculptureparkel$,
  $sculptureparkru_t$Парк скульптур Айя-Напы$sculptureparkru_t$,
  $sculptureparkru$Этот музей под открытым небом, расположенный на холме с видом на море, гармонично сочетает искусство с природой. Прогулка по парку предлагает не только культурный опыт, но и захватывающий панорамный вид на бескрайнее синее море.$sculptureparkru$,
  $sculptureparkzh_t$雕塑公园 (Sculpture Park)$sculptureparkzh_t$,
  $sculptureparkzh$这座露天博物馆坐落在俯瞰大海的山丘上，将艺术与自然完美融合。漫步在公园中，不仅能体验文化，还能居高临下地欣赏下方无尽蓝色海洋的壮丽全景。$sculptureparkzh$,
  false,
  34.9878,
  34.0675,
  'famagusta'
),
(
  'profitisilias',
  'views',
  'images/profitisilias.jpg',
  'https://maps.google.com/?q=35.01849,34.0411776',
  $profitisiliasen_t$Profitis Ilias Church$profitisiliasen_t$,
  $profitisiliasen$Perched on a steep rocky outcrop 100 meters above town, this 14th-century chapel requires climbing over 150 steps. The reward is arguably the best vantage point in the region, offering breathtaking daytime and nighttime views of the entire Protaras coastline.$profitisiliasen$,
  $profitisiliasel_t$Εκκλησία Προφήτη Ηλία$profitisiliasel_t$,
  $profitisiliasel$Σκαρφαλωμένο σε έναν απότομο βράχο 100 μέτρα πάνω από την πόλη, το εκκλησάκι του 14ου αιώνα απαιτεί ανάβαση 150+ σκαλοπατιών. Η ανταμοιβή είναι αναμφίβολα η καλύτερη πανοραμική θέα της περιοχής, τόσο την ημέρα όσο και τη νύχτα, σε όλη την ακτογραμμή του Πρωταρά.$profitisiliasel$,
  $profitisiliasru_t$Церковь Пророка Ильи (Протарас)$profitisiliasru_t$,
  $profitisiliasru$Чтобы добраться до этой часовни 14-го века, расположенной на крутой скале в 100 метрах над городом, нужно преодолеть более 150 ступенек. Наградой станет, пожалуй, лучшая смотровая площадка в регионе, откуда открывается захватывающий вид на все побережье Протараса днем и ночью.$profitisiliasru$,
  $profitisiliaszh_t$圣伊莱亚斯教堂 (Profitis Ilias)$profitisiliaszh_t$,
  $profitisiliaszh$这座建于 14 世纪的教堂坐落在高出城镇 100 米的陡峭岩石上，需要攀登 150 多级台阶。但您将获得该地区最好的观景台作为回报，日夜都能欣赏到整个普罗塔拉斯海岸线令人叹为观止的景色。$profitisiliaszh$,
  false,
  35.01849,
  34.0411776,
  'famagusta'
),
(
  'konnosoverlook',
  'views',
  'images/konnosoverlook.jpg',
  'https://maps.google.com/?q=34.9988,34.0735',
  $konnosoverlooken_t$Konnos Bay Overlook$konnosoverlooken_t$,
  $konnosoverlooken$Before descending to the beach, the pine-fringed cliffs above Konnos Bay offer a spectacular viewpoint. Looking down into the sheltered, emerald-colored natural lagoon surrounded by dramatic nature is a sight you will never forget.$konnosoverlooken$,
  $konnosoverlookel_t$Θέα Κόλπου Κόννου$konnosoverlookel_t$,
  $konnosoverlookel$Πριν κατεβείτε στην παραλία, οι πευκόφυτοι γκρεμοί πάνω από τον Κόλπο του Κόννου προσφέρουν μια εκπληκτική οπτική. Η θέα από ψηλά στην απάνεμη, σμαραγδένια φυσική λιμνοθάλασσα που περιβάλλεται από άγρια φύση, είναι μια εικόνα που δεν θα ξεχάσετε ποτέ.$konnosoverlookel$,
  $konnosoverlookru_t$Смотровая площадка Коннос Бэй$konnosoverlookru_t$,
  $konnosoverlookru$Перед спуском на пляж со скал, поросших соснами, над заливом Коннос открывается впечатляющий вид. Взгляд сверху на защищенную естественную лагуну изумрудного цвета, окруженную первозданной природой, — это зрелище, которое вы никогда не забудете.$konnosoverlookru$,
  $konnosoverlookzh_t$康诺斯湾观景点 (Konnos Bay)$konnosoverlookzh_t$,
  $konnosoverlookzh$在下到海滩之前，康诺斯湾上方长满松树的悬崖提供了一个壮观的视角。俯瞰被壮丽自然环绕的避风翡翠色天然泻湖，将是您终生难忘的景象。$konnosoverlookzh$,
  false,
  34.9988,
  34.0735,
  'famagusta'
),
(
  'peacemonument',
  'views',
  'images/peacemonument.jpg',
  'https://maps.google.com/?q=34.9619,34.0865',
  $peacemonumenten_t$Cape Greco Monument of Peace$peacemonumenten_t$,
  $peacemonumenten$Located at one of the highest points of the Cape Greco peninsula, this viewpoint offers a sweeping, uninterrupted 360-degree panorama. You can gaze out over the endless Mediterranean horizon and the rugged eastern coastline.$peacemonumenten$,
  $peacemonumentel_t$Μνημείο Ειρήνης Κάβο Γκρέκο$peacemonumentel_t$,
  $peacemonumentel$Σε ένα από τα υψηλότερα σημεία της χερσονήσου του Κάβο Γκρέκο, αυτό το σημείο προσφέρει μια σαρωτική, ανεμπόδιστη πανοραμική θέα 360 μοιρών. Μπορείτε να αγναντέψετε τον απέραντο μεσογειακό ορίζοντα και την άγρια ανατολική ακτογραμμή.$peacemonumentel$,
  $peacemonumentru_t$Монумент Мира на Каво Греко$peacemonumentru_t$,
  $peacemonumentru$С этой смотровой площадки, расположенной на одной из самых высоких точек полуострова Каво Греко, открывается беспрепятственная 360-градусная панорама. Вы можете бесконечно любоваться горизонтом Средиземного моря и скалистым восточным побережьем.$peacemonumentru$,
  $peacemonumentzh_t$和平纪念碑观景点 (Cape Greco)$peacemonumentzh_t$,
  $peacemonumentzh$这个观景点位于格雷科角半岛的最高点之一，提供一览无余的 360 度全景。您可以眺望无尽的地中海地平线和崎岖的东部海岸线。$peacemonumentzh$,
  false,
  34.9619,
  34.0865,
  'famagusta'
),
(
  'kourionview',
  'views',
  'images/kourion.jpg',
  'https://maps.google.com/?q=34.6644446,32.8880218',
  $kourionviewen_t$Kourion Amphitheatre$kourionviewen_t$,
  $kourionviewen$Perched on a dramatic coastal cliff, the Archaeological Site of Kourion is one of Cyprus's most spectacular ancient city-kingdoms. Sitting on the top steps of the restored amphitheater allows you to enjoy sweeping, cinematic views of the Mediterranean Sea.$kourionviewen$,
  $kourionviewel_t$Αρχαίο Θέατρο Κουρίου$kourionviewel_t$,
  $kourionviewel$Σκαρφαλωμένος σε έναν εντυπωσιακό παραθαλάσσιο γκρεμό, ο Αρχαιολογικός Χώρος του Κουρίου είναι ένα από τα πιο θεαματικά αρχαία βασίλεια. Καθισμένοι στα ψηλότερα σκαλοπάτια του αναστηλωμένου αμφιθεάτρου, μπορείτε να απολαύσετε πανοραμική, κινηματογραφική θέα στη Μεσόγειο Θάλασσα.$kourionviewel$,
  $kourionviewru_t$Амфитеатр Курион$kourionviewru_t$,
  $kourionviewru$Расположенный на живописном прибрежном утесе, археологический комплекс Курион является одним из самых впечатляющих древних городов-государств Кипра. Сидя на верхних ступенях отреставрированного амфитеатра, вы можете наслаждаться панорамным, кинематографичным видом на Средиземное море.$kourionviewru$,
  $kourionviewzh_t$库里翁圆形剧场 (Kourion)$kourionviewzh_t$,
  $kourionviewzh$库里翁考古遗址坐落于壮观的海岸悬崖上，是塞浦路斯最壮观的古代城邦之一。坐在修复后的圆形剧场最高层台阶上，您可以欣赏到地中海令人叹为观止的电影般全景。$kourionviewzh$,
  false,
  34.6644446,
  32.8880218,
  'limassol'
),
(
  'limassolmarinaview',
  'views',
  'images/limassolmarina.webp',
  'https://maps.google.com/?q=34.6702125,33.040437',
  $limassolmarinaviewen_t$Limassol Marina$limassolmarinaviewen_t$,
  $limassolmarinaviewen$A premier destination combining luxury living and yachting facilities, set against the backdrop of the sparkling Mediterranean Sea. Walking along the promenade or dining at a waterfront cafe provides a chic, modern view of luxury yachts and the city skyline.$limassolmarinaviewen$,
  $limassolmarinaviewel_t$Μαρίνα Λεμεσού$limassolmarinaviewel_t$,
  $limassolmarinaviewel$Ένας κορυφαίος προορισμός που συνδυάζει την πολυτελή διαβίωση και τις εγκαταστάσεις γιοτ, με φόντο τη λαμπερή Μεσόγειο. Μια βόλτα στον πεζόδρομο προσφέρει μια κομψή, μοντέρνα θέα γεμάτη πολυτελή σκάφη και τον ορίζοντα της πόλης.$limassolmarinaviewel$,
  $limassolmarinaviewru_t$Лимассол Марина$limassolmarinaviewru_t$,
  $limassolmarinaviewru$Первоклассное направление, сочетающее в себе роскошную жизнь и яхтенные удобства на фоне сверкающего Средиземного моря. Прогулка по набережной предлагает шикарный современный вид на роскошные яхты и городской пейзаж.$limassolmarinaviewru$,
  $limassolmarinaviewzh_t$利马索尔码头 (Limassol Marina)$limassolmarinaviewzh_t$,
  $limassolmarinaviewzh$这是一个将奢华生活和游艇设施融为一体的顶级目的地，以波光粼粼的地中海为背景。沿着海滨长廊漫步，可以欣赏到豪华游艇和城市天际线的别致现代景观。$limassolmarinaviewzh$,
  false,
  34.6702125,
  33.040437,
  'limassol'
),
(
  'governorsrocks',
  'views',
  'images/governors.jpg',
  'https://maps.google.com/?q=34.7123267,33.2713302',
  $governorsrocksen_t$Governor's Beach White Rocks$governorsrocksen_t$,
  $governorsrocksen$Just outside the city, this unique coastal landscape features brilliant white chalk rocks contrasting sharply with the deep blue sea. It is a striking visual location, perfect for dramatic nature photography.$governorsrocksen$,
  $governorsrocksel_t$Λευκά Βράχια στην Ακτή του Κυβερνήτη$governorsrocksel_t$,
  $governorsrocksel$Λίγο έξω από την πόλη, αυτό το μοναδικό παράκτιο τοπίο διαθέτει λαμπερά λευκά κιμωλιούχα βράχια που κάνουν έντονη αντίθεση με τη βαθιά μπλε θάλασσα. Είναι μια εντυπωσιακή τοποθεσία, ιδανική για δραματικές φωτογραφίες της φύσης.$governorsrocksel$,
  $governorsrocksru_t$Белые скалы на Губернаторском пляже$governorsrocksru_t$,
  $governorsrocksru$Этот уникальный прибрежный ландшафт недалеко от города отличается ослепительно белыми меловыми скалами, резко контрастирующими с темно-синим морем. Это поразительно красивое место, идеально подходящее для эффектной природной фотографии.$governorsrocksru$,
  $governorsrockszh_t$总督海滩白岩 (Governor's Beach)$governorsrockszh_t$,
  $governorsrockszh$在城外，这种独特的海岸景观以明亮的白色白垩岩与深蓝色的海水形成鲜明对比为特色。这是一个极具视觉冲击力的地点，非常适合拍摄震撼的自然风光照片。$governorsrockszh$,
  false,
  34.7123267,
  33.2713302,
  'limassol'
),
(
  'saltlake',
  'views',
  'images/saltlake.jpg',
  'https://maps.google.com/?q=34.9008,33.6215',
  $saltlakeen_t$Larnaca Salt Lake$saltlakeen_t$,
  $saltlakeen$A complex network of four salt lakes that offers a mesmerizing, mirror-like view. During the winter months, the lake transforms into a spectacular pink canvas as thousands of flamingos gather, creating a magical sunset view.$saltlakeen$,
  $saltlakeel_t$Αλυκή Λάρνακας$saltlakeel_t$,
  $saltlakeel$Ένα εντυπωσιακό δίκτυο τεσσάρων αλμυρών λιμνών που προσφέρει θέα σαν καθρέφτης. Τους χειμερινούς μήνες, η λίμνη μεταμορφώνεται σε έναν θεαματικό ροζ καμβά, καθώς συγκεντρώνονται χιλιάδες φλαμίνγκο, δημιουργώντας ένα μαγικό σκηνικό στο ηλιοβασίλεμα.$saltlakeel$,
  $saltlakeru_t$Соленое озеро Ларнаки$saltlakeru_t$,
  $saltlakeru$Сложная сеть из четырех соленых озер, предлагающая завораживающий зеркальный вид. В зимние месяцы озеро превращается во впечатляющее розовое полотно, когда здесь собираются тысячи фламинго, создавая волшебный пейзаж на закате.$saltlakeru$,
  $saltlakezh_t$拉纳卡盐湖 (Larnaca Salt Lake)$saltlakezh_t$,
  $saltlakezh$由四个盐湖组成的复杂网络，呈现出如镜面般迷人的景色。在冬季，当成千上万的火烈鸟聚集在此，湖面就会变成壮观的粉红色画布，营造出神奇的日落景观。$saltlakezh$,
  false,
  34.9008,
  33.6215,
  'larnaca'
),
(
  'stavrovouni',
  'views',
  'images/stavrovouni.jpg',
  'https://maps.google.com/?q=34.8856,33.437',
  $stavrovounien_t$Stavrovouni Monastery$stavrovounien_t$,
  $stavrovounien$Perched on the peak of a solitary mountain, this ancient monastery offers an unmatched, eagle-eye view of the entire Larnaca region, the coastline, and the surrounding countryside.$stavrovounien$,
  $stavrovouniel_t$Μονή Σταυροβουνίου$stavrovouniel_t$,
  $stavrovouniel$Σκαρφαλωμένο στην κορυφή ενός απομονωμένου βουνού, αυτό το αρχαίο μοναστήρι προσφέρει μια απαράμιλλη θέα "από το μάτι του αετού" σε ολόκληρη την επαρχία Λάρνακας, την ακτογραμμή και την ύπαιθρο.$stavrovouniel$,
  $stavrovouniru_t$Монастырь Ставровуни$stavrovouniru_t$,
  $stavrovouniru$Этот древний монастырь, расположенный на вершине одинокой горы, предлагает непревзойденный вид с высоты птичьего полета на весь регион Ларнаки, побережье и окружающую загородную местность.$stavrovouniru$,
  $stavrovounizh_t$斯塔夫罗武尼修道院 (Stavrovouni)$stavrovounizh_t$,
  $stavrovounizh$这座古老的修道院坐落在一座孤立的山峰上，提供无与伦比的鹰眼视角，可以俯瞰整个拉纳卡地区、海岸线和周围的乡村。$stavrovounizh$,
  false,
  34.8856,
  33.437,
  'larnaca'
),
(
  'finikoudesview',
  'views',
  'images/foinikoudes.jpg',
  'https://maps.google.com/?q=34.9140131,33.6383829',
  $finikoudesviewen_t$Finikoudes Promenade$finikoudesviewen_t$,
  $finikoudesviewen$The city's most famous palm-tree-lined promenade is a vibrant hub. Sitting at one of the elevated cafes or simply strolling down the path offers spectacular, classic views of the Mediterranean blending with the city's lively energy.$finikoudesviewen$,
  $finikoudesviewel_t$Φοινικούδες$finikoudesviewel_t$,
  $finikoudesviewel$Ο πιο διάσημος παραλιακός πεζόδρομος της πόλης, γεμάτος φοίνικες. Καθισμένοι σε ένα από τα υπερυψωμένα καφέ, η θέα προσφέρει έναν κλασικό μεσογειακό ορίζοντα που δένει αρμονικά με τη ζωντανή ενέργεια της πόλης.$finikoudesviewel$,
  $finikoudesviewru_t$Финикудес (Ларнака)$finikoudesviewru_t$,
  $finikoudesviewru$Самая известная набережная города, обсаженная пальмами, является оживленным центром. Сидя в одном из возвышающихся кафе или просто прогуливаясь по аллее, вы можете наслаждаться классическим видом на Средиземное море, сливающимся с энергией города.$finikoudesviewru$,
  $finikoudesviewzh_t$菲尼库德斯 (Finikoudes)$finikoudesviewzh_t$,
  $finikoudesviewzh$这座城市最著名的棕榈树林荫长廊是一个充满活力的中心。坐在高处的咖啡馆里，或者只是沿着小路漫步，都能欣赏到地中海与城市活力交融的壮丽经典美景。$finikoudesviewzh$,
  false,
  34.9140131,
  33.6383829,
  'larnaca'
),
(
  'shacolastower',
  'views',
  'images/shacolastower.jpg',
  'https://maps.google.com/?q=35.171,33.3615',
  $shacolastoweren_t$Shacolas Tower Observatory$shacolastoweren_t$,
  $shacolastoweren$Located on the 11th floor in the heart of the capital, this observatory provides a fascinating 360-degree panoramic view of Nicosia. It is the best place to view the layout of Europe's last divided capital and the distant Kyrenia mountains.$shacolastoweren$,
  $shacolastowerel_t$Παρατηρητήριο Πύργου Σιακόλα$shacolastowerel_t$,
  $shacolastowerel$Στον 11ο όροφο, στην καρδιά της πρωτεύουσας, αυτό το παρατηρητήριο παρέχει μια συναρπαστική πανοραμική θέα 360 μοιρών της Λευκωσίας. Είναι το καλύτερο σημείο για να δείτε από ψηλά την τελευταία διχοτομημένη πρωτεύουσα της Ευρώπης και την οροσειρά του Πενταδακτύλου.$shacolastowerel$,
  $shacolastowerru_t$Обсерватория башни Шаколас$shacolastowerru_t$,
  $shacolastowerru$Эта обсерватория, расположенная на 11 этаже в самом центре столицы, предлагает захватывающий 360-градусный панорамный вид на Никосию. Это лучшее место, чтобы увидеть планировку последней разделенной столицы Европы и горы Кирения вдали.$shacolastowerru$,
  $shacolastowerzh_t$沙科拉斯塔观景台 (Shacolas Tower)$shacolastowerzh_t$,
  $shacolastowerzh$位于首都中心 11 层的这家观景台提供了迷人的尼科西亚 360 度全景。这里是俯瞰欧洲最后一个分裂首都的布局和远处凯里尼亚山脉的最佳地点。$shacolastowerzh$,
  false,
  35.171,
  33.3615,
  'nicosia'
),
(
  'athalassaview',
  'views',
  'images/athalassa-nicosia-cyprus.jpg',
  'https://maps.google.com/?q=35.1270481,33.3920351',
  $athalassaviewen_t$Athalassa National Forest Park$athalassaviewen_t$,
  $athalassaviewen$A lush green oasis spanning over 840 hectares. Standing by the park's beautiful lake provides a serene, picturesque nature view, offering a peaceful escape from the concrete environment of the city.$athalassaviewen$,
  $athalassaviewel_t$Εθνικό Δασικό Πάρκο Αθαλάσσας$athalassaviewel_t$,
  $athalassaviewel$Μια καταπράσινη όαση με έκταση άνω των 840 εκταρίων. Στεκόμενοι δίπλα στην πανέμορφη λίμνη του πάρκου, απολαμβάνετε μια γαλήνια, γραφική θέα της φύσης, που αποτελεί την τέλεια απόδραση από το αστικό τοπίο.$athalassaviewel$,
  $athalassaviewru_t$Национальный лесной парк Аталасса$athalassaviewru_t$,
  $athalassaviewru$Пышный зеленый оазис площадью более 840 гектаров. Стоя у красивого озера парка, вы можете наслаждаться безмятежным, живописным видом на природу, предлагающим спокойный отдых от городской суеты.$athalassaviewru$,
  $athalassaviewzh_t$阿塔拉萨国家森林公园 (Athalassa)$athalassaviewzh_t$,
  $athalassaviewzh$一片占地超过 840 公顷的郁郁葱葱的绿洲。站在公园美丽的湖畔，可以欣赏到宁静如画的自然风光，为您提供远离城市喧嚣的宁静避风港。$athalassaviewzh$,
  false,
  35.1270481,
  33.3920351,
  'nicosia'
),
(
  'eleftheriasquare',
  'views',
  'images/eleftheriasquare.jpg',
  'https://maps.google.com/?q=35.1696,33.3612',
  $eleftheriasquareen_t$Eleftheria Square$eleftheriasquareen_t$,
  $eleftheriasquareen$Designed by Zaha Hadid, the modern Eleftheria Square offers a stunning architectural viewpoint. Standing on the futuristic bridge, you can view the striking contrast between the centuries-old Venetian walls below and the modern cityscape.$eleftheriasquareen$,
  $eleftheriasquareel_t$Πλατεία Ελευθερίας$eleftheriasquareel_t$,
  $eleftheriasquareel$Σχεδιασμένη από τη Zaha Hadid, η σύγχρονη Πλατεία Ελευθερίας προσφέρει μια εκπληκτική αρχιτεκτονική θέα. Στεκόμενοι στη φουτουριστική γέφυρα, μπορείτε να δείτε την εντυπωσιακή αντίθεση μεταξύ των αιωνόβιων Ενετικών τειχών από κάτω και του σύγχρονου αστικού τοπίου.$eleftheriasquareel$,
  $eleftheriasquareru_t$Площадь Элефтерия$eleftheriasquareru_t$,
  $eleftheriasquareru$Современная площадь Элефтерия, спроектированная Захой Хадид, предлагает потрясающий архитектурный вид. Стоя на футуристическом мосту, вы можете увидеть поразительный контраст между многовековыми венецианскими стенами внизу и современным городским пейзажем.$eleftheriasquareru$,
  $eleftheriasquarezh_t$自由广场 (Eleftheria Square)$eleftheriasquarezh_t$,
  $eleftheriasquarezh$由扎哈·哈迪德 (Zaha Hadid) 设计的现代自由广场 (Eleftheria Square) 提供了令人惊叹的建筑视角。站在充满未来感的桥上，您可以看到下方拥有数百年历史的威尼斯城墙与现代城市景观之间形成的鲜明对比。$eleftheriasquarezh$,
  false,
  35.1696,
  33.3612,
  'nicosia'
)
on conflict (id) do update set
  category = excluded.category,
  image_url = excluded.image_url,
  map_link = excluded.map_link,
  title_en = excluded.title_en,
  desc_en = excluded.desc_en,
  title_el = excluded.title_el,
  desc_el = excluded.desc_el,
  title_ru = excluded.title_ru,
  desc_ru = excluded.desc_ru,
  title_zh = excluded.title_zh,
  desc_zh = excluded.desc_zh,
  lat = excluded.lat,
  lng = excluded.lng,
  town = excluded.town;
