insert into public.places (
  id, category, image_url, phone, website, map_link,
  title_en, desc_en, title_el, desc_el, title_ru, desc_ru, title_zh, desc_zh,
  subcategory, is_best_of_month, lat, lng, town
) values
(
  'hiltonnicosia',
  'hotels',
  'images/hiltonnicosia.jpg',
  null,
  'https://www.hilton.com/en/hotels/nicchhi-hilton-nicosia/',
  'https://maps.google.com/?q=35.1633942,33.3271155',
  $hiltonnicosiaen_t$Hilton Nicosia$hiltonnicosiaen_t$,
  $hiltonnicosiaen$Located in a prime area of the capital, Hilton Nicosia offers a luxurious and tranquil environment ideal for both business and leisure travelers. Guests can relax in the massive lagoon-style outdoor pool or rejuvenate at the award-winning spa and wellness center. The hotel also features top-tier dining options, including authentic traditional dishes and international cuisine, ensuring a premium stay.$hiltonnicosiaen$,
  $hiltonnicosiael_t$Hilton Nicosia$hiltonnicosiael_t$,
  $hiltonnicosiael$Σε προνομιακή τοποθεσία της πρωτεύουσας, το Hilton Nicosia προσφέρει ένα πολυτελές και γαλήνιο περιβάλλον, ιδανικό για επαγγελματίες και τουρίστες. Οι επισκέπτες μπορούν να χαλαρώσουν στην τεράστια εξωτερική πισίνα σε στιλ λιμνοθάλασσας ή να αναζωογονηθούν στο βραβευμένο σπα και κέντρο ευεξίας. Το ξενοδοχείο διαθέτει επίσης κορυφαίες επιλογές εστίασης, με αυθεντικά παραδοσιακά πιάτα και διεθνή κουζίνα, εξασφαλίζοντας μια premium διαμονή.$hiltonnicosiael$,
  $hiltonnicosiaru_t$Hilton Nicosia$hiltonnicosiaru_t$,
  $hiltonnicosiaru$Отель Hilton Nicosia, расположенный в престижном районе столицы, предлагает роскошную и спокойную обстановку, идеально подходящую как для деловых путешественников, так и для туристов. Гости могут расслабиться в огромном открытом бассейне в виде лагуны или восстановить силы в превосходном спа-центре. В отеле также есть первоклассные рестораны, предлагающие аутентичные традиционные блюда и блюда международной кухни, что гарантирует проживание премиум-класса.$hiltonnicosiaru$,
  $hiltonnicosiazh_t$尼科西亚希尔顿酒店 (Hilton Nicosia)$hiltonnicosiazh_t$,
  $hiltonnicosiazh$尼科西亚希尔顿酒店 (Hilton Nicosia) 位于首都的黄金地段，提供奢华宁静的环境，是商务和休闲旅客的理想选择。客人可以在巨大的泻湖式室外游泳池放松身心，或在屡获殊荣的水疗和健康中心恢复活力。酒店还提供顶级的餐饮选择，包括地道的传统菜肴和国际美食，确保为您带来优质的住宿体验。$hiltonnicosiazh$,
  null,
  false,
  35.1633942,
  33.3271155,
  'nicosia'
),
(
  'cleopatra',
  'hotels',
  'images/cleopatra.jpg',
  null,
  'https://cleopatra.com.cy/',
  'https://maps.google.com/?q=35.1651272,33.3587086',
  $cleopatraen_t$Cleopatra Hotel$cleopatraen_t$,
  $cleopatraen$Situated right in the bustling center of Nicosia, Cleopatra Hotel is a classic choice known for its excellent service and elegant accommodations. It features a stylish outdoor swimming pool surrounded by olive trees, offering an oasis of calm within the city. Guests can enjoy exceptional meals at the on-site Lounge Bar and Restaurant, making it a convenient and sophisticated urban base.$cleopatraen$,
  $cleopatrael_t$Cleopatra Hotel$cleopatrael_t$,
  $cleopatrael$Στην καρδιά του πολυσύχναστου κέντρου της Λευκωσίας, το Cleopatra Hotel είναι μια κλασική επιλογή γνωστή για την εξαιρετική εξυπηρέτηση και τα κομψά δωμάτια. Διαθέτει μια στιλάτη εξωτερική πισίνα που περιβάλλεται από ελιές, προσφέροντας μια όαση ηρεμίας μέσα στην πόλη. Οι επισκέπτες μπορούν να απολαύσουν εξαιρετικά γεύματα στο Lounge Bar και εστιατόριο του ξενοδοχείου, καθιστώντας το μια βολική και εκλεπτυσμένη αστική βάση.$cleopatrael$,
  $cleopatraru_t$Cleopatra Hotel$cleopatraru_t$,
  $cleopatraru$Отель Cleopatra, расположенный в самом оживленном центре Никосии, является классическим выбором, известным своим отличным сервисом и элегантными номерами. К услугам гостей стильный открытый бассейн, окруженный оливковыми деревьями, предлагающий оазис спокойствия в городе. Гости могут насладиться исключительными блюдами в лаундж-баре и ресторане на территории отеля, что делает его удобной и изысканной городской базой.$cleopatraru$,
  $cleopatrazh_t$艳后酒店 (Cleopatra Hotel)$cleopatrazh_t$,
  $cleopatrazh$艳后酒店 (Cleopatra Hotel) 位于繁华的尼科西亚市中心，以其卓越的服务和优雅的住宿环境而闻名，是一个经典的选择。酒店设有一个被橄榄树环绕的时尚室外游泳池，在城市中提供了一片宁静的绿洲。客人可以在酒店内的酒廊酒吧和餐厅享用美味佳肴，使其成为一个便利精致的城市基地。$cleopatrazh$,
  null,
  false,
  35.1651272,
  33.3587086,
  'nicosia'
),
(
  'semeli',
  'hotels',
  'images/semeli.jpg',
  null,
  'https://www.semelihotel.com.cy/',
  'https://maps.google.com/?q=35.1580453,33.3706242',
  $semelien_t$Semeli Hotel$semelien_t$,
  $semelien$Semeli Hotel is a modern, boutique-style hotel offering a warm and welcoming atmosphere just a short walk from Nicosia's main business and shopping districts. The rooms are fully equipped with state-of-the-art amenities, ensuring maximum comfort for every guest. The hotel's highly regarded restaurant serves a delicious fusion of Mediterranean and international flavors, perfect for business lunches or romantic dinners.$semelien$,
  $semeliel_t$Semeli Hotel$semeliel_t$,
  $semeliel$Το Semeli Hotel είναι ένα μοντέρνο, boutique ξενοδοχείο που προσφέρει ζεστή και φιλόξενη ατμόσφαιρα, σε μικρή απόσταση με τα πόδια από τις εμπορικές και επιχειρηματικές περιοχές της Λευκωσίας. Τα δωμάτια είναι πλήρως εξοπλισμένα με υπερσύγχρονες ανέσεις, εξασφαλίζοντας μέγιστη άνεση για κάθε επισκέπτη. Το φημισμένο εστιατόριο του ξενοδοχείου σερβίρει έναν υπέροχο συνδυασμό μεσογειακών και διεθνών γεύσεων, ιδανικό για επαγγελματικά γεύματα ή ρομαντικά δείπνα.$semeliel$,
  $semeliru_t$Semeli Hotel$semeliru_t$,
  $semeliru$Semeli — это современный бутик-отель, предлагающий теплую и гостеприимную атмосферу в нескольких минутах ходьбы от главных деловых и торговых районов Никосии. Номера полностью оснащены самыми современными удобствами, что обеспечивает максимальный комфорт для каждого гостя. В высоко оцененном ресторане отеля подают восхитительные блюда средиземноморской и международной кухни, которые идеально подходят для деловых обедов или романтических ужинов.$semeliru$,
  $semelizh_t$塞梅利酒店 (Semeli Hotel)$semelizh_t$,
  $semelizh$塞梅利酒店 (Semeli Hotel) 是一家现代化的精品酒店，提供温馨宜人的氛围，距离尼科西亚的主要商业和购物区仅有很短的步行路程。客房配备了最先进的设施，确保每位客人都能获得最大的舒适度。酒店备受推崇的餐厅供应美味的地中海和国际融合风味，是商务午餐或浪漫晚餐的完美选择。$semelizh$,
  null,
  false,
  35.1580453,
  33.3706242,
  'nicosia'
),
(
  'ciaostelio',
  'hotels',
  'images/ciaostelio.jpg?v=hotel2',
  null,
  'https://theciaostelio.com/',
  'https://maps.google.com/?q=34.8931297,33.6384064',
  $ciaostelioen_t$The Ciao Stelio Deluxe Hotel$ciaostelioen_t$,
  $ciaostelioen$This elegant, adults-only boutique hotel is located right by the famous Mackenzie Beach, offering sweeping views of the Mediterranean Sea. The Ciao Stelio is renowned for its personalized service, luxurious design, and tranquil, sophisticated atmosphere. Its exquisite dining venue serves gourmet dishes accompanied by a carefully curated wine list, ensuring a memorable culinary journey.$ciaostelioen$,
  $ciaostelioel_t$The Ciao Stelio Deluxe Hotel$ciaostelioel_t$,
  $ciaostelioel$Αυτό το κομψό, boutique ξενοδοχείο μόνο για ενήλικες βρίσκεται ακριβώς δίπλα στη διάσημη παραλία Μακένζι, προσφέροντας ανεμπόδιστη θέα στη Μεσόγειο. Το The Ciao Stelio φημίζεται για την εξατομικευμένη εξυπηρέτηση, τον πολυτελή σχεδιασμό του και τη γαλήνια, εκλεπτυσμένη ατμόσφαιρα. Το εξαιρετικό εστιατόριό του σερβίρει γκουρμέ πιάτα που συνοδεύονται από μια προσεκτικά επιλεγμένη λίστα κρασιών, εξασφαλίζοντας ένα αξέχαστο γαστρονομικό ταξίδι.$ciaostelioel$,
  $ciaostelioru_t$The Ciao Stelio Deluxe Hotel$ciaostelioru_t$,
  $ciaostelioru$Этот элегантный бутик-отель только для взрослых расположен прямо у знаменитого пляжа Маккензи, откуда открывается потрясающий вид на Средиземное море. Отель The Ciao Stelio славится индивидуальным обслуживанием, роскошным дизайном и спокойной, изысканной атмосферой. В его изысканном ресторане подают деликатесы в сопровождении тщательно подобранной карты вин, что гарантирует незабываемое кулинарное путешествие.$ciaostelioru$,
  $ciaosteliozh_t$The Ciao Stelio Deluxe Hotel$ciaosteliozh_t$,
  $ciaosteliozh$这家优雅的仅限成人入住的精品酒店就位于著名的麦肯齐海滩 (Mackenzie Beach) 旁，享有地中海的一览无余的美景。The Ciao Stelio 以其个性化的服务、奢华的设计和宁静精致的氛围而闻名。其精致的餐厅供应美味佳肴，并配有精心挑选的酒单，确保为您带来难忘的烹饪之旅。$ciaosteliozh$,
  null,
  false,
  34.8931297,
  33.6384064,
  'larnaca'
),
(
  'goldenbay',
  'hotels',
  'images/goldenbay.jpg?v=hotel2',
  null,
  'https://goldenbay.com.cy/',
  'https://maps.google.com/?q=34.977541,33.6917523',
  $goldenbayen_t$Golden Bay Beach Hotel$goldenbayen_t$,
  $goldenbayen$Set on a sandy stretch of coastline in Larnaca, the Golden Bay Beach Hotel is a prestigious five-star resort perfect for families and couples alike. The property boasts impressive landscaped gardens, sprawling outdoor pools, and a luxurious spa offering holistic treatments. Guests can choose from a variety of excellent restaurants on-site, serving everything from authentic Cypriot meze to refined international cuisine.$goldenbayen$,
  $goldenbayel_t$Golden Bay Beach Hotel$goldenbayel_t$,
  $goldenbayel$Χτισμένο σε μια αμμώδη ακτογραμμή της Λάρνακας, το Golden Bay Beach Hotel είναι ένα πολυτελές πεντάστερο θέρετρο, ιδανικό για οικογένειες και ζευγάρια. Το κατάλυμα διαθέτει εντυπωσιακούς κήπους, τεράστιες εξωτερικές πισίνες και ένα πολυτελές σπα που προσφέρει ολιστικές θεραπείες. Οι επισκέπτες μπορούν να επιλέξουν από μια ποικιλία εξαιρετικών εστιατορίων στις εγκαταστάσεις, που σερβίρουν από αυθεντικούς κυπριακούς μεζέδες μέχρι εκλεπτυσμένη διεθνή κουζίνα.$goldenbayel$,
  $goldenbayru_t$Golden Bay Beach Hotel$goldenbayru_t$,
  $goldenbayru$Престижный пятизвездочный курортный отель Golden Bay Beach, расположенный на песчаном побережье Ларнаки, идеально подходит как для семей, так и для пар. Отель может похвастаться впечатляющими ландшафтными садами, обширными открытыми бассейнами и роскошным спа-центром, предлагающим холистические процедуры. Гости могут выбрать один из множества отличных ресторанов на территории, где подают все: от аутентичного кипрского мезе до изысканных блюд интернациональной кухни.$goldenbayru$,
  $goldenbayzh_t$金湾海滩酒店 (Golden Bay Beach Hotel)$goldenbayzh_t$,
  $goldenbayzh$金湾海滩酒店 (Golden Bay Beach Hotel) 坐落于拉纳卡的沙滩海岸线上，是一家享有盛誉的五星级度假村，非常适合家庭和情侣入住。该酒店拥有令人印象深刻的园林景观、广阔的室外游泳池和提供全方位护理的豪华水疗中心。客人可以选择酒店内的各种一流餐厅，品尝从地道的塞浦路斯小吃到精致的国际美食。$goldenbayzh$,
  null,
  false,
  34.977541,
  33.6917523,
  'larnaca'
),
(
  'lebay',
  'hotels',
  'images/lebay.jpg?v=hotel2',
  '+357 24 205 100',
  'https://lebayhotel.com.cy/',
  'https://maps.google.com/?q=34.9637644,33.6626459',
  $lebayen_t$Lebay Beach Hotel$lebayen_t$,
  $lebayen$Lebay Beach Hotel features a chic, minimalist design and sits proudly on the edge of a pristine, twin-bay beach just outside Larnaca's center. With a stunning infinity pool that seems to merge with the sea, it is a haven for modern travelers seeking relaxation. The hotel’s restaurant focuses on fresh, seasonal ingredients, creating light and flavorful Mediterranean dishes with a contemporary twist.$lebayen$,
  $lebayel_t$Lebay Beach Hotel$lebayel_t$,
  $lebayel$Το Lebay Beach Hotel διαθέτει κομψό, μινιμαλιστικό σχεδιασμό και δεσπόζει σε μια παρθένα παραλία λίγο έξω από το κέντρο της Λάρνακας. Με μια εντυπωσιακή πισίνα υπερχείλισης που μοιάζει να ενώνεται με τη θάλασσα, είναι ένα καταφύγιο για μοντέρνους ταξιδιώτες που αναζητούν χαλάρωση. Το εστιατόριο του ξενοδοχείου εστιάζει σε φρέσκα, εποχιακά υλικά, δημιουργώντας ελαφριά και γευστικά μεσογειακά πιάτα με σύγχρονη πινελιά.$lebayel$,
  $lebayru_t$Lebay Beach Hotel$lebayru_t$,
  $lebayru$Отель Lebay Beach отличается шикарным минималистичным дизайном и гордо возвышается на краю нетронутого пляжа в заливе недалеко от центра Ларнаки. С потрясающим пейзажным бассейном, который, кажется, сливается с морем, это рай для современных путешественников, ищущих расслабления. Ресторан отеля специализируется на свежих сезонных ингредиентах, создавая легкие и ароматные средиземноморские блюда в современном исполнении.$lebayru$,
  $lebayzh_t$乐贝海滩酒店 (Lebay Beach Hotel)$lebayzh_t$,
  $lebayzh$乐贝海滩酒店 (Lebay Beach Hotel) 采用别致的极简主义设计，傲然矗立在拉纳卡市中心外一片原始双湾海滩的边缘。这里拥有一个似乎与大海融为一体的令人惊叹的无边泳池，是寻求放松的现代旅行者的避风港。酒店的餐厅专注于新鲜的当季食材，打造出带有现代风味的清淡可口的地中海菜肴。$lebayzh$,
  null,
  false,
  34.9637644,
  33.6626459,
  'larnaca'
),
(
  'amathus',
  'hotels',
  'images/amathus.jpg?v=hotel2',
  null,
  'https://www.amathuslimassol.com/',
  'https://maps.google.com/?q=34.709194,33.1328935',
  $amathusen_t$Amathus Beach Hotel$amathusen_t$,
  $amathusen$A distinguished member of the Leading Hotels of the World, Amathus Beach Hotel in Limassol is a sanctuary of world-class luxury and comfort. Set amidst lush tropical gardens and fronting the Mediterranean, it offers state-of-the-art spa facilities, indoor and outdoor pools, and direct beach access. Dining here is a culinary event, featuring award-winning restaurants that serve everything from fresh seafood to premium Asian fusion.$amathusen$,
  $amathusel_t$Amathus Beach Hotel$amathusel_t$,
  $amathusel$Ένα διακεκριμένο μέλος των Leading Hotels of the World, το Amathus Beach Hotel στη Λεμεσό είναι ένα καταφύγιο παγκόσμιας κλάσης πολυτέλειας και άνεσης. Χτισμένο μέσα σε καταπράσινους τροπικούς κήπους μπροστά στη Μεσόγειο, προσφέρει υπερσύγχρονες εγκαταστάσεις σπα, εσωτερικές και εξωτερικές πισίνες και άμεση πρόσβαση στην παραλία. Το φαγητό εδώ είναι ένα γαστρονομικό γεγονός, με βραβευμένα εστιατόρια που σερβίρουν από φρέσκα θαλασσινά μέχρι premium ασιατική fusion κουζίνα.$amathusel$,
  $amathusru_t$Amathus Beach Hotel$amathusru_t$,
  $amathusru$Отель Amathus Beach в Лимассоле, выдающийся член ассоциации Leading Hotels of the World, является оазисом роскоши и комфорта мирового класса. Расположенный среди пышных тропических садов на берегу Средиземного моря, он предлагает ультрасовременные спа-услуги, крытый и открытый бассейны и прямой выход к пляжу. Питание здесь — это кулинарное событие, в отмеченных наградами ресторанах подают все: от свежих морепродуктов до премиального азиатского фьюжн.$amathusru$,
  $amathuszh_t$利马索尔阿马苏斯海滩酒店 (Amathus Beach Hotel)$amathuszh_t$,
  $amathuszh$利马索尔阿马苏斯海滩酒店 (Amathus Beach Hotel) 是世界立鼎世酒店集团 (Leading Hotels of the World) 的尊贵成员，是世界级奢华与舒适的避风港。酒店坐落于郁郁葱葱的热带花园中，面向地中海，提供最先进的水疗设施、室内和室外游泳池以及直接通往海滩的通道。在这里用餐是一场烹饪盛宴，屡获殊荣的餐厅供应从新鲜海鲜到优质亚洲融合菜肴的各种美食。$amathuszh$,
  null,
  false,
  34.709194,
  33.1328935,
  'limassol'
),
(
  'medbeach',
  'hotels',
  'images/medbeach.jpg?v=hotel2',
  null,
  'https://www.medbeach.com/',
  'https://maps.google.com/?q=34.7096008,33.130216',
  $medbeachen_t$Mediterranean Beach Hotel$medbeachen_t$,
  $medbeachen$Perfectly situated on the sandy beaches of Limassol, this four-star superior resort boasts an incredible terraced swimming pool surrounded by palm trees. It is highly praised for its warm hospitality, excellent family facilities, and a dedicated kids' club that guarantees fun for younger guests. Food lovers will be delighted by its diverse dining venues, including a highly acclaimed traditional Cypriot taverna right on the premises.$medbeachen$,
  $medbeachel_t$Mediterranean Beach Hotel$medbeachel_t$,
  $medbeachel$Σε ιδανική τοποθεσία πάνω στις αμμώδεις παραλίες της Λεμεσού, αυτό το superior θέρετρο τεσσάρων αστέρων διαθέτει μια απίστευτη πισίνα πολλαπλών επιπέδων που περιβάλλεται από φοίνικες. Επαινείται ιδιαίτερα για τη ζεστή φιλοξενία, τις εξαιρετικές οικογενειακές εγκαταστάσεις και ένα οργανωμένο kids' club που εγγυάται διασκέδαση για τους μικρούς επισκέπτες. Οι λάτρεις του φαγητού θα ενθουσιαστούν από τους ποικίλους χώρους εστίασης, συμπεριλαμβανομένης μιας εξαιρετικής παραδοσιακής κυπριακής ταβέρνας.$medbeachel$,
  $medbeachru_t$Mediterranean Beach Hotel$medbeachru_t$,
  $medbeachru$Этот четырехзвездочный курортный отель повышенной комфортности идеально расположен на песчаных пляжах Лимассола. К услугам гостей невероятный многоуровневый бассейн, окруженный пальмами. Он высоко ценится за теплое гостеприимство, отличные условия для семейного отдыха и специальный детский клуб, гарантирующий веселье для маленьких гостей. Любители вкусно поесть будут в восторге от разнообразных ресторанов, включая высоко оцененную традиционную кипрскую таверну прямо на территории.$medbeachru$,
  $medbeachzh_t$地中海海滩酒店 (Mediterranean Beach Hotel)$medbeachzh_t$,
  $medbeachzh$这家四星级高级度假村完美地坐落于利马索尔的沙滩上，拥有一个被棕榈树环绕的令人惊叹的梯田式游泳池。它因其热情的待客之道、出色的一流家庭设施以及为小客人带来无限欢乐的专属儿童俱乐部而备受赞誉。美食爱好者将对其多样化的餐饮场所感到满意，包括酒店内备受好评的传统塞浦路斯小酒馆。$medbeachzh$,
  null,
  false,
  34.7096008,
  33.130216,
  'limassol'
),
(
  'royalapollonia',
  'hotels',
  'images/royalapollonia.jpg?v=hotel2',
  null,
  'https://www.louishotels.com/royal-apollonia',
  'https://maps.google.com/?q=34.6976215,33.0955127',
  $royalapolloniaen_t$The Royal Apollonia$royalapolloniaen_t$,
  $royalapolloniaen$An elegant seafront hotel in Limassol, The Royal Apollonia combines modern design with an array of premium holiday facilities. Its defining feature is the massive free-form outdoor pool that provides the perfect setting for sun-drenched relaxation. Guests can indulge in diverse culinary experiences, ranging from authentic Japanese cuisine at Akakiko to vibrant Greek dishes at the Meze by Elliniko restaurant.$royalapolloniaen$,
  $royalapolloniael_t$The Royal Apollonia$royalapolloniael_t$,
  $royalapolloniael$Ένα κομψό παραθαλάσσιο ξενοδοχείο στη Λεμεσό, το The Royal Apollonia συνδυάζει τον μοντέρνο σχεδιασμό με μια σειρά από premium εγκαταστάσεις διακοπών. Χαρακτηριστικό του είναι η τεράστια εξωτερική πισίνα ελεύθερου σχήματος που προσφέρει το τέλειο σκηνικό για ηλιόλουστη χαλάρωση. Οι επισκέπτες μπορούν να απολαύσουν ποικίλες γαστρονομικές εμπειρίες, από αυθεντική ιαπωνική κουζίνα στο Akakiko μέχρι εξαιρετικά ελληνικά πιάτα στο εστιατόριο Meze by Elliniko.$royalapolloniael$,
  $royalapolloniaru_t$The Royal Apollonia$royalapolloniaru_t$,
  $royalapolloniaru$Элегантный прибрежный отель The Royal Apollonia в Лимассоле сочетает в себе современный дизайн и множество первоклассных удобств для отдыха. Его отличительной чертой является массивный открытый бассейн произвольной формы, который идеально подходит для отдыха на солнце. Гости могут насладиться разнообразными кулинарными изысками: от аутентичной японской кухни в ресторане Akakiko до ярких греческих блюд в ресторане Meze by Elliniko.$royalapolloniaru$,
  $royalapolloniazh_t$皇家阿波罗尼亚酒店 (The Royal Apollonia)$royalapolloniazh_t$,
  $royalapolloniazh$皇家阿波罗尼亚酒店 (The Royal Apollonia) 是利马索尔一家优雅的海滨酒店，将现代设计与一系列优质度假设施完美结合。其标志性特征是巨大的自由形态室外游泳池，为阳光普照的休闲时光提供了完美的环境。客人可以尽情享受多样化的烹饪体验，从 Akakiko 的正宗日本料理到 Meze by Elliniko 餐厅充满活力的希腊菜肴，应有尽有。$royalapolloniazh$,
  null,
  false,
  34.6976215,
  33.0955127,
  'limassol'
),
(
  'annabelle',
  'hotels',
  'images/annabelle.jpg?v=hotel2',
  null,
  'https://www.annabelle.com.cy/',
  'https://maps.google.com/?q=34.7552807,32.4174452',
  $annabelleen_t$Annabelle Hotel$annabelleen_t$,
  $annabelleen$Centrally located on the Paphos seafront, the Annabelle Hotel is a chic oasis renowned for its lush tropical gardens and cascading waterfalls. This luxurious resort provides an atmosphere of classic elegance, complete with free-flowing pools and an exquisite rooftop spa offering panoramic sea views. Dining at the Annabelle is a true pleasure, with several top-tier restaurants serving farm-to-table ingredients and gourmet Mediterranean dishes.$annabelleen$,
  $annabelleel_t$Annabelle Hotel$annabelleel_t$,
  $annabelleel$Σε κεντρική τοποθεσία στον παραλιακό δρόμο της Πάφου, το ξενοδοχείο Annabelle είναι μια κομψή όαση φημισμένη για τους καταπράσινους τροπικούς κήπους και τους καταρράκτες του. Αυτό το πολυτελές θέρετρο προσφέρει μια ατμόσφαιρα κλασικής κομψότητας, με εντυπωσιακές πισίνες και ένα εξαιρετικό σπα στον τελευταίο όροφο με πανοραμική θέα στη θάλασσα. Το φαγητό στο Annabelle είναι πραγματική απόλαυση, με αρκετά κορυφαία εστιατόρια που σερβίρουν γκουρμέ μεσογειακά πιάτα με φρέσκα ντόπια υλικά.$annabelleel$,
  $annabelleru_t$Annabelle Hotel$annabelleru_t$,
  $annabelleru$Отель Annabelle, расположенный в самом центре набережной Пафоса, — это шикарный оазис, известный своими пышными тропическими садами и каскадными водопадами. Этот роскошный курорт предлагает атмосферу классической элегантности, дополненную великолепными бассейнами и изысканным спа-центром на крыше с панорамным видом на море. Питание в Annabelle — это истинное удовольствие: в нескольких первоклассных ресторанах подают ингредиенты с фермы на стол и изысканные блюда средиземноморской кухни.$annabelleru$,
  $annabellezh_t$安娜贝尔酒店 (Annabelle Hotel)$annabellezh_t$,
  $annabellezh$安娜贝尔酒店 (Annabelle Hotel) 位于帕福斯海滨的中心地带，是一片别致的绿洲，以其郁郁葱葱的热带花园和层叠的瀑布而闻名。这家豪华度假村提供经典优雅的氛围，配有令人惊叹的游泳池和享有大海全景的精致屋顶水疗中心。在安娜贝尔用餐是一种真正的享受，这里有几家顶级餐厅供应从农场到餐桌的食材和美味的地中海菜肴。$annabellezh$,
  null,
  false,
  34.7552807,
  32.4174452,
  'paphos'
),
(
  'almyra',
  'hotels',
  'images/almyra.jpg',
  null,
  'https://www.almyra.com/',
  'https://maps.google.com/?q=34.7541191,32.4189117',
  $almyraen_t$Almyra Hotel$almyraen_t$,
  $almyraen$Almyra Hotel is a vibrant and stylish design hotel set along the beautiful Paphos promenade, just a short walk from the historic castle. It perfectly balances a family-friendly environment with contemporary, minimalist luxury, featuring multiple freshwater pools and a serene adults-only spa. Guests can enjoy exceptional culinary experiences, ranging from fresh sushi to traditional Cypriot meze right by the water's edge.$almyraen$,
  $almyrael_t$Almyra Hotel$almyrael_t$,
  $almyrael$Το Almyra είναι ένα ζωντανό και στιλάτο design hotel στον όμορφο παραλιακό πεζόδρομο της Πάφου, σε μικρή απόσταση από το ιστορικό κάστρο. Εξισορροπεί τέλεια το φιλικό προς την οικογένεια περιβάλλον με τη σύγχρονη, μινιμαλιστική πολυτέλεια, διαθέτοντας πισίνες γλυκού νερού και ένα γαλήνιο σπα μόνο για ενήλικες. Οι επισκέπτες μπορούν να απολαύσουν εξαιρετικές γαστρονομικές εμπειρίες, από φρέσκο σούσι μέχρι παραδοσιακούς κυπριακούς μεζέδες ακριβώς δίπλα στο κύμα.$almyrael$,
  $almyraru_t$Almyra Hotel$almyraru_t$,
  $almyraru$Дизайн-отель Almyra — это яркий и стильный отель, расположенный на красивой набережной Пафоса, всего в нескольких минутах ходьбы от исторического замка. Он идеально сочетает в себе семейную атмосферу с современной минималистской роскошью, располагая несколькими бассейнами с пресной водой и тихим спа-центром только для взрослых. Гости могут насладиться исключительными кулинарными изысками: от свежих суши до традиционного кипрского мезе прямо у кромки воды.$almyraru$,
  $almyrazh_t$阿尔米拉酒店 (Almyra Hotel)$almyrazh_t$,
  $almyrazh$阿尔米拉酒店 (Almyra Hotel) 是一家充满活力且时尚的设计酒店，坐落在美丽的帕福斯海滨长廊沿岸，距离历史悠久的城堡仅有很短的步行路程。它完美地平衡了适合家庭的环境与现代极简主义的奢华，拥有多个淡水游泳池和一个宁静的仅限成人入住的水疗中心。客人可以在水边享受卓越的烹饪体验，从新鲜的寿司到传统的塞浦路斯小吃应有尽有。$almyrazh$,
  null,
  false,
  34.7541191,
  32.4189117,
  'paphos'
),
(
  'asimina',
  'hotels',
  'images/asimina.jpg?v=hotel2',
  '+357 26 964333',
  'https://www.asimina-cbh.com/',
  'https://maps.google.com/?q=34.7392,32.435',
  $asiminaen_t$Constantinou Bros Asimina Suites Hotel$asiminaen_t$,
  $asiminaen$Catering strictly to adults, the Asimina Suites Hotel is a five-star luxurious sanctuary situated on a quiet, private sandy beach in Paphos. The property consists entirely of spacious, exquisitely decorated suites, ensuring unmatched privacy and comfort. With a world-class Elixir Spa, private cabanas by the pools, and romantic beachfront dining, it is the ultimate destination for couples and honeymooners.$asiminaen$,
  $asiminael_t$Constantinou Bros Asimina Suites Hotel$asiminael_t$,
  $asiminael$Απευθυνόμενο αυστηρά σε ενήλικες, το Asimina Suites Hotel είναι ένα πεντάστερο πολυτελές καταφύγιο χτισμένο σε μια ήσυχη, ιδιωτική αμμώδη παραλία στην Πάφο. Το κατάλυμα αποτελείται εξ ολοκλήρου από ευρύχωρες, εξαιρετικά διακοσμημένες σουίτες, εξασφαλίζοντας απαράμιλλη ιδιωτικότητα και άνεση. Με το παγκόσμιας κλάσης Elixir Spa, ιδιωτικές καμπάνες δίπλα στις πισίνες και ρομαντικά δείπνα στην παραλία, είναι ο απόλυτος προορισμός για ζευγάρια.$asiminael$,
  $asiminaru_t$Asimina Suites Hotel$asiminaru_t$,
  $asiminaru$Пятизвездочный отель Asimina Suites, предназначенный исключительно для взрослых, представляет собой роскошный оазис, расположенный на тихом частном песчаном пляже в Пафосе. Отель полностью состоит из просторных, изысканно оформленных люксов, обеспечивающих непревзойденную уединенность и комфорт. С первоклассным спа-центром Elixir, частными беседками у бассейнов и романтическими ужинами на берегу моря — это идеальное место для пар и молодоженов.$asiminaru$,
  $asiminazh_t$阿西米纳套房酒店 (Asimina Suites Hotel)$asiminazh_t$,
  $asiminazh$阿西米纳套房酒店 (Asimina Suites Hotel) 专为成人提供服务，是一家五星级的豪华圣地，坐落于帕福斯宁静的私人沙滩上。该酒店完全由宽敞且装饰精美的套房组成，确保无与伦比的隐私和舒适。凭借世界一流的 Elixir 水疗中心、池畔私人小屋和浪漫的海滨餐饮，它是情侣和度蜜月者的终极目的地。$asiminazh$,
  null,
  false,
  34.7392,
  32.435,
  'paphos'
),
(
  'adamsbeach',
  'hotels',
  'images/adamsbeach.jpg?v=hotel2',
  null,
  'https://www.adams.com.cy/',
  'https://maps.google.com/?q=34.9883841,33.9666124',
  $adamsbeachen_t$Adams Beach Hotel$adamsbeachen_t$,
  $adamsbeachen$Sitting right on the golden sands of the famous Nissi Bay, Adams Beach Hotel offers an unbeatable location and a bustling holiday atmosphere. The resort features a fantastic water park with slides, a lazy river, and multiple pools, making it an absolute paradise for families. For those seeking relaxation, the luxurious Coral Spa and an impressive variety of on-site dining options provide the perfect balance.$adamsbeachen$,
  $adamsbeachel_t$Adams Beach Hotel$adamsbeachel_t$,
  $adamsbeachel$Ακριβώς πάνω στη χρυσή άμμο του διάσημου Nissi Bay, το Adams Beach Hotel προσφέρει μια ασυναγώνιστη τοποθεσία και μια ζωντανή ατμόσφαιρα διακοπών. Το θέρετρο διαθέτει ένα φανταστικό water park με νεροτσουλήθρες, lazy river και πολλές πισίνες, καθιστώντας το έναν απόλυτο παράδεισο για οικογένειες. Για όσους αναζητούν χαλάρωση, το πολυτελές Coral Spa και η εντυπωσιακή ποικιλία επιλογών εστίασης προσφέρουν την τέλεια ισορροπία.$adamsbeachel$,
  $adamsbeachru_t$Adams Beach Hotel$adamsbeachru_t$,
  $adamsbeachru$Отель Adams Beach, расположенный прямо на золотых песках знаменитого залива Нисси, предлагает непревзойденное расположение и оживленную атмосферу отдыха. На курорте есть фантастический аквапарк с горками, ленивая река и несколько бассейнов, что делает его абсолютным раем для семей. Для тех, кто ищет расслабления, роскошный спа-центр Coral и впечатляющее разнообразие ресторанов на территории обеспечивают идеальный баланс.$adamsbeachru$,
  $adamsbeachzh_t$亚当斯海滩酒店 (Adams Beach Hotel)$adamsbeachzh_t$,
  $adamsbeachzh$亚当斯海滩酒店 (Adams Beach Hotel) 坐落于著名的尼斯湾 (Nissi Bay) 的金色沙滩上，提供无与伦比的地理位置和热闹的度假氛围。度假村拥有梦幻般的水上乐园、滑梯、漂流河和多个游泳池，使其成为家庭的绝对天堂。对于寻求放松的客人，豪华的珊瑚水疗中心 (Coral Spa) 和各种令人印象深刻的内部餐饮选择提供了完美的平衡。$adamsbeachzh$,
  null,
  false,
  34.9883841,
  33.9666124,
  'famagusta'
),
(
  'grecianbay',
  'hotels',
  'images/grecianbay.jpg?v=hotel2',
  null,
  'https://www.grecianbay.com/',
  'https://maps.google.com/?q=34.9851455,34.0081791',
  $grecianbayen_t$Grecian Bay Hotel$grecianbayen_t$,
  $grecianbayen$A prestigious five-star property, Grecian Bay Hotel is nestled on a spectacular sandy beach in Ayia Napa, boasting panoramic views of the crystal-clear sea. The hotel offers expansive, elegantly furnished rooms, a world-class wellness center, and a beautiful indoor pool. Its culinary excellence shines through its renowned seafood restaurant, which serves the freshest catch of the day directly by the shore.$grecianbayen$,
  $grecianbayel_t$Grecian Bay Hotel$grecianbayel_t$,
  $grecianbayel$Ένα υψηλού κύρους πεντάστερο κατάλυμα, το Grecian Bay Hotel είναι φωλιασμένο σε μια θεαματική αμμώδη παραλία της Αγίας Νάπας, με πανοραμική θέα στην κρυστάλλινη θάλασσα. Το ξενοδοχείο προσφέρει ευρύχωρα, κομψά επιπλωμένα δωμάτια, ένα κέντρο ευεξίας παγκόσμιας κλάσης και μια όμορφη εσωτερική πισίνα. Η γαστρονομική του υπεροχή λάμπει μέσα από το φημισμένο εστιατόριο θαλασσινών του, το οποίο σερβίρει φρέσκα ψάρια ακριβώς δίπλα στην ακτή.$grecianbayel$,
  $grecianbayru_t$Grecian Bay Hotel$grecianbayru_t$,
  $grecianbayru$Престижный пятизвездочный отель Grecian Bay расположен на потрясающем песчаном пляже в Айя-Напе, откуда открывается панорамный вид на кристально чистое море. Отель предлагает просторные, элегантно обставленные номера, первоклассный оздоровительный центр и красивый крытый бассейн. Его кулинарное мастерство сияет в известном ресторане морепродуктов, где подают свежайший улов дня прямо на берегу.$grecianbayru$,
  $grecianbayzh_t$希腊海湾酒店 (Grecian Bay Hotel)$grecianbayzh_t$,
  $grecianbayzh$希腊海湾酒店 (Grecian Bay Hotel) 是一家享有盛誉的五星级酒店，坐落在圣纳帕壮观的沙滩上，享有清澈大海的全景。酒店提供宽敞且布置优雅的客房、世界一流的健康中心和美丽的室内游泳池。其著名的海鲜餐厅供应直接在岸边捕捞的最新鲜的海鲜，彰显了其卓越的烹饪水平。$grecianbayzh$,
  null,
  false,
  34.9851455,
  34.0081791,
  'famagusta'
),
(
  'amarande',
  'hotels',
  'images/amarande.jpg?v=hotel2',
  null,
  'https://www.amarandehotel.com/',
  'https://maps.google.com/?q=34.9861,34.013',
  $amarandeen_t$Amarande (Adults Only)$amarandeen_t$,
  $amarandeen$Positioned in an elevated, tranquil spot just steps from the beach in Ayia Napa, Amarande is a premium adults-only hotel defined by its ultra-modern design and sophisticated vibe. It boasts an expansive outdoor pool deck with stunning sea views and a highly luxurious wellness spa. The hotel takes pride in its fine-dining restaurants, providing guests with innovative gastronomic creations in a highly romantic setting.$amarandeen$,
  $amarandeel_t$Amarande (Adults Only)$amarandeel_t$,
  $amarandeel$Σε μια υπερυψωμένη, ήσυχη τοποθεσία λίγα βήματα από την παραλία στην Αγία Νάπα, το Amarande είναι ένα premium ξενοδοχείο μόνο για ενήλικες, που ξεχωρίζει για τον υπερσύγχρονο σχεδιασμό και την εκλεπτυσμένη του ατμόσφαιρα. Διαθέτει μια τεράστια εξωτερική πισίνα με εκπληκτική θέα στη θάλασσα και ένα εξαιρετικά πολυτελές σπα ευεξίας. Το ξενοδοχείο υπερηφανεύεται για τα εστιατόρια υψηλής γαστρονομίας, παρέχοντας στους επισκέπτες καινοτόμες δημιουργίες σε ένα εξαιρετικά ρομαντικό περιβάλλον.$amarandeel$,
  $amaranderu_t$Amarande (Adults Only)$amaranderu_t$,
  $amaranderu$Расположенный на возвышенном тихом месте в нескольких шагах от пляжа в Айя-Напе, Amarande — это первоклассный отель только для взрослых, отличающийся ультрасовременным дизайном и изысканной атмосферой. Он может похвастаться просторной открытой террасой у бассейна с потрясающим видом на море и роскошным спа-центром. Отель гордится своими ресторанами высокой кухни, предлагающими гостям новаторские гастрономические творения в очень романтической обстановке.$amaranderu$,
  $amarandezh_t$阿玛兰德 (Amarande)$amarandezh_t$,
  $amarandezh$阿玛兰德 (Amarande) 是一家仅限成人的高档酒店，位于圣纳帕海滩仅几步之遥的宁静高处，以其超现代的设计和精致的氛围而闻名。酒店拥有宽敞的室外游泳池甲板，享有迷人的海景，并设有一个极其豪华的健康水疗中心。酒店引以为傲的是其高级餐厅，在高度浪漫的环境中为客人提供创新的美食创意。$amarandezh$,
  null,
  false,
  34.9861,
  34.013,
  'famagusta'
),
(
  'capobay',
  'hotels',
  'images/capobay.jpg?v=hotel2',
  null,
  'https://www.capobay.com/',
  'https://maps.google.com/?q=35.0127161,34.0569744',
  $capobayen_t$Capo Bay Hotel$capobayen_t$,
  $capobayen$Located directly on the famous Fig Tree Bay, Capo Bay Hotel perfectly merges modern design with natural beachside beauty. The resort boasts spectacular swimming pools and an award-winning spa that offers treatments inspired by the Mediterranean. From elegant sushi to traditional local flavors, its diverse dining options ensure that every guest's culinary desires are thoroughly satisfied.$capobayen$,
  $capobayel_t$Capo Bay Hotel$capobayel_t$,
  $capobayel$Χτισμένο ακριβώς πάνω στον διάσημο Κόλπο της Συκιάς (Fig Tree Bay), το Capo Bay Hotel συνδυάζει τέλεια τον μοντέρνο σχεδιασμό με τη φυσική ομορφιά της παραλίας. Το θέρετρο διαθέτει θεαματικές πισίνες και ένα βραβευμένο σπα που προσφέρει θεραπείες εμπνευσμένες από τη Μεσόγειο. Από κομψό σούσι μέχρι παραδοσιακές τοπικές γεύσεις, οι ποικίλες επιλογές εστίασης εξασφαλίζουν ότι οι γαστρονομικές επιθυμίες κάθε επισκέπτη ικανοποιούνται πλήρως.$capobayel$,
  $capobayru_t$Capo Bay Hotel$capobayru_t$,
  $capobayru$Отель Capo Bay, расположенный прямо в знаменитой бухте Фигового дерева (Fig Tree Bay), идеально сочетает в себе современный дизайн с природной красотой пляжа. Курорт может похвастаться впечатляющими бассейнами и отмеченным наградами спа-центром, предлагающим процедуры, вдохновленные Средиземноморьем. От элегантных суши до традиционных местных вкусов — разнообразные рестораны гарантируют, что кулинарные желания каждого гостя будут полностью удовлетворены.$capobayru$,
  $capobayzh_t$卡波湾酒店 (Capo Bay Hotel)$capobayzh_t$,
  $capobayzh$卡波湾酒店 (Capo Bay Hotel) 直接坐落在著名的无花果树湾 (Fig Tree Bay) 上，将现代设计与自然海滩美景完美融合。度假村拥有壮观的游泳池和屡获殊荣的水疗中心，提供受地中海启发的护理服务。从优雅的寿司到传统的当地风味，其多样化的餐饮选择确保每位客人的烹饪愿望都能得到充分满足。$capobayzh$,
  null,
  false,
  35.0127161,
  34.0569744,
  'famagusta'
),
(
  'grecianpark',
  'hotels',
  'images/grecianpark.jpg?v=hotel2',
  null,
  'https://www.grecianpark.com/',
  'https://maps.google.com/?q=34.9854314,34.0680222',
  $grecianparken_t$Grecian Park Hotel$grecianparken_t$,
  $grecianparken$Nestled beautifully on a cliffside bordering the Cape Greco National Park, Grecian Park Hotel offers some of the most breathtaking panoramic views on the island. Overlooking the serene Konnos Bay, it features top-class amenities including a modern spa, tennis courts, and secluded beach access. With its iconic cliff-top bar and high-end restaurants, it is a haven for nature lovers and luxury seekers alike.$grecianparken$,
  $grecianparkel_t$Grecian Park Hotel$grecianparkel_t$,
  $grecianparkel$Φωλιασμένο όμορφα στην άκρη ενός γκρεμού που συνορεύει με το Εθνικό Πάρκο Κάβο Γκρέκο, το Grecian Park Hotel προσφέρει ίσως την πιο μαγευτική πανοραμική θέα στο νησί. Με θέα στον γαλήνιο Κόλπο του Κόννου, διαθέτει ανέσεις κορυφαίας κατηγορίας, όπως ένα μοντέρνο σπα, γήπεδα τένις και απομονωμένη πρόσβαση στην παραλία. Με το εμβληματικό μπαρ στον βράχο και τα πολυτελή εστιατόρια του, είναι ένα καταφύγιο για τους λάτρεις της φύσης και της πολυτέλειας.$grecianparkel$,
  $grecianparkru_t$Grecian Park Hotel$grecianparkru_t$,
  $grecianparkru$Отель Grecian Park, живописно расположенный на скале на границе национального парка Каво Греко, предлагает одни из самых захватывающих панорамных видов на острове. С видом на безмятежную бухту Коннос, он предлагает первоклассные удобства, включая современный спа-центр, теннисные корты и уединенный выход на пляж. С его культовым баром на вершине скалы и элитными ресторанами это рай как для любителей природы, так и для искателей роскоши.$grecianparkru$,
  $grecianparkzh_t$希腊公园酒店 (Grecian Park Hotel)$grecianparkzh_t$,
  $grecianparkzh$希腊公园酒店 (Grecian Park Hotel) 完美地坐落在与格雷科角国家公园接壤的悬崖边，享有岛上一些最令人叹为观止的全景。酒店俯瞰着宁静的康诺斯湾 (Konnos Bay)，提供一流的设施，包括现代化的水疗中心、网球场和僻静的海滩通道。凭借其标志性的悬崖顶酒吧和高档餐厅，它是自然爱好者和奢华追求者的避风港。$grecianparkzh$,
  null,
  false,
  34.9854314,
  34.0680222,
  'famagusta'
),
(
  'constantinosthegreat',
  'hotels',
  'images/constantinosthegreat.jpg?v=hotel2',
  null,
  'https://www.constantinosthegreat.com/',
  'https://maps.google.com/?q=35.0177417,34.0515821',
  $constantinosthegreaten_t$Constantinos the Great Beach Hotel$constantinosthegreaten_t$,
  $constantinosthegreaten$Dominating the vibrant beachfront of Protaras, Constantinos the Great Beach Hotel is a massive luxury resort offering spectacular views over the Mediterranean Sea. Guests can enjoy its sprawling lagoon pool, direct access to the golden sands of Sunrise Beach, and comprehensive leisure facilities. The hotel also hosts excellent themed buffet dinners and a la carte restaurants, creating a perfect lively holiday atmosphere.$constantinosthegreaten$,
  $constantinosthegreatel_t$Constantinos the Great Beach Hotel$constantinosthegreatel_t$,
  $constantinosthegreatel$Κυριαρχώντας στο ζωντανό παραλιακό μέτωπο του Πρωταρά, το Constantinos the Great Beach Hotel είναι ένα τεράστιο πολυτελές θέρετρο που προσφέρει εκπληκτική θέα στη Μεσόγειο. Οι επισκέπτες μπορούν να απολαύσουν την τεράστια πισίνα-λιμνοθάλασσα, την άμεση πρόσβαση στη χρυσή άμμο της παραλίας Sunrise και ολοκληρωμένες εγκαταστάσεις αναψυχής. Το ξενοδοχείο φιλοξενεί επίσης εξαιρετικά θεματικά δείπνα μπουφέ και a la carte εστιατόρια, δημιουργώντας μια τέλεια και ζωντανή ατμόσφαιρα διακοπών.$constantinosthegreatel$,
  $constantinosthegreatru_t$Constantinos the Great Beach Hotel$constantinosthegreatru_t$,
  $constantinosthegreatru$Огромный роскошный курортный отель Constantinos the Great Beach, возвышающийся на оживленном побережье Протараса, предлагает захватывающий вид на Средиземное море. Гости могут насладиться обширным бассейном-лагуной, прямым доступом к золотым пескам пляжа Санрайз и широким спектром удобств для отдыха. В отеле также проводятся отличные тематические ужины в формате "шведский стол" и работают рестораны a la carte, создавая идеальную оживленную атмосферу праздника.$constantinosthegreatru$,
  $constantinosthegreatzh_t$康斯坦丁大帝海滩酒店 (Constantinos the Great Beach Hotel)$constantinosthegreatzh_t$,
  $constantinosthegreatzh$康斯坦丁大帝海滩酒店 (Constantinos the Great Beach Hotel) 雄踞普罗塔拉斯充满活力的海滨，是一家提供壮丽地中海美景的大型豪华度假村。客人可以享受其广阔的泻湖游泳池、直接通往日出海滩 (Sunrise Beach) 的金色沙滩以及全面的休闲设施。酒店还举办一流的主题自助晚餐并设有单点餐厅，营造出完美热闹的度假氛围。$constantinosthegreatzh$,
  null,
  false,
  35.0177417,
  34.0515821,
  'famagusta'
)
on conflict (id) do update set
  category = excluded.category,
  image_url = excluded.image_url,
  phone = excluded.phone,
  website = excluded.website,
  map_link = excluded.map_link,
  title_en = excluded.title_en,
  desc_en = excluded.desc_en,
  title_el = excluded.title_el,
  desc_el = excluded.desc_el,
  title_ru = excluded.title_ru,
  desc_ru = excluded.desc_ru,
  title_zh = excluded.title_zh,
  desc_zh = excluded.desc_zh,
  subcategory = excluded.subcategory,
  lat = excluded.lat,
  lng = excluded.lng,
  town = excluded.town;
