insert into public.places (
  id, category, image_url, phone, website, map_link,
  title_en, desc_en, title_el, desc_el, title_ru, desc_ru, title_zh, desc_zh,
  subcategory, is_best_of_month, lat, lng, town
) values
(
  'cyfield',
  'realestate',
  'images/cyfield.jpg',
  '+357 22 427230',
  'https://www.cyfieldgroup.com/',
  'https://maps.google.com/?q=35.1427979,33.3738718',
  $cyfielden_t$Cyfield Group$cyfielden_t$,
  $cyfielden$Cyfield Group is one of the premier real estate developers and construction giants in Cyprus. Renowned for engineering landmark high-rises such as 360 Nicosia, the tallest residential tower in the capital, the company specializes in modern apartments, commercial towers, and infrastructure projects built to the highest architectural standards.$cyfielden$,
  $cyfieldel_t$Cyfield Group$cyfieldel_t$,
  $cyfieldel$Ο Όμιλος Cyfield είναι μία από τις κορυφαίες εταιρείες ανάπτυξης γης και κατασκευών στην Κύπρο. Φημισμένος για εμβληματικά ψηλά κτίρια, όπως το 360 Nicosia, τον ψηλότερο οικιστικό πύργο της πρωτεύουσας, ειδικεύεται σε μοντέρνα διαμερίσματα, εμπορικά κτίρια και έργα υποδομής υψηλότατων προδιαγραφών.$cyfieldel$,
  $cyfieldru_t$Cyfield Group$cyfieldru_t$,
  $cyfieldru$Cyfield Group — один из ведущих застройщиков и строительных гигантов на Кипре. Известная возведением знаковых небоскребов, таких как 360 Nicosia (самая высокая жилая башня столицы), компания специализируется на современных квартирах, коммерческих зданиях и инфраструктурных проектах высшего стандарта.$cyfieldru$,
  $cyfieldzh_t$Cyfield Group$cyfieldzh_t$,
  $cyfieldzh$Cyfield Group 是塞浦路斯首屈一指的房地产开发和建筑巨头之一。该公司以建造地标性高层建筑而闻名，例如首都最高住宅塔楼 360 Nicosia，专注于按照最高建筑标准打造现代公寓、商业大厦和基础设施项目。$cyfieldzh$,
  null,
  false,
  35.1427979,
  33.3738718,
  'nicosia'
),
(
  'psaras',
  'realestate',
  'images/psaras.jpg',
  '+357 22 330084',
  'https://npsaras.com/',
  'https://maps.google.com/?q=35.1550048,33.3929264',
  $psarasen_t$N. Psaras Construction$psarasen_t$,
  $psarasen$With decades of proven expertise, N. Psaras Construction is a distinguished developer in Nicosia delivering premium residential and commercial spaces. They focus on energy-efficient housing, sustainable design, and bespoke architectural finishes, making them a trusted choice for upscale urban living.$psarasen$,
  $psarasel_t$N. Psaras Construction$psarasel_t$,
  $psarasel$Με δεκαετίες αποδεδειγμένης εμπειρίας, η N. Psaras Construction είναι μια διακεκριμένη κατασκευαστική εταιρεία στη Λευκωσία με premium οικιστικά και επαγγελματικά ακίνητα. Εστιάζει σε ενεργειακά αποδοτικές κατοικίες, βιώσιμο σχεδιασμό και προσεγμένα αρχιτεκτονικά φινιρίσματα.$psarasel$,
  $psarasru_t$N. Psaras Construction$psarasru_t$,
  $psarasru$Обладая многолетним подтвержденным опытом, N. Psaras Construction является признанным застройщиком в Никосии, реализующим первоклассные жилые и коммерческие объекты. Компания ориентирована на энергоэффективное жилье, экологичный дизайн и индивидуальные архитектурные решения.$psarasru$,
  $psaraszh_t$N. Psaras Construction$psaraszh_t$,
  $psaraszh$凭借数十年的丰富经验，N. Psaras Construction 是尼科西亚著名的开发商，提供高端住宅和商业空间。他们专注于节能住宅、可持续设计和定制建筑装饰，是追求高品质都市生活的信赖之选。$psaraszh$,
  null,
  false,
  35.1550048,
  33.3929264,
  'nicosia'
),
(
  'leda',
  'realestate',
  'images/leda.jpg',
  null,
  null,
  'https://maps.google.com/?q=35.117,33.315',
  $ledaen_t$Leda Properties$ledaen_t$,
  $ledaen$Leda Properties is a boutique developer based in Nicosia, specializing in contemporary apartments and elegant townhouses across prime suburban areas. Their commitment to minimalist design, functional layouts, and transparent customer service offers excellent opportunities for homeowners and investors alike.$ledaen$,
  $ledael_t$Leda Properties$ledael_t$,
  $ledael$Η Leda Properties είναι μια boutique εταιρεία ανάπτυξης ακινήτων με έδρα τη Λευκωσία, με εξειδίκευση σε σύγχρονα διαμερίσματα και κομψές μεζονέτες σε προνομιακές περιοχές. Η έμφαση στον μινιμαλιστικό σχεδιασμό και η αξιοπιστία της την καθιστούν ιδανική επιλογή για αγοραστές και επενδυτές.$ledael$,
  $ledaru_t$Leda Properties$ledaru_t$,
  $ledaru$Leda Properties — бутик-девелопер из Никосии, специализирующийся на современных квартирах и элегантных таунхаусах в престижных пригородных районах. Приверженность минималистичному дизайну и функциональным планировкам привлекает как покупателей жилья, так и инвесторов.$ledaru$,
  $ledazh_t$Leda Properties$ledazh_t$,
  $ledazh$Leda Properties 是一家总部位于尼科西亚的精品开发商，专注于在黄金郊区开发现代公寓和优雅联排别墅。他们对极简设计、实用空间布局和透明服务的追求，为购房者和投资者提供了卓越的选择。$ledazh$,
  null,
  false,
  35.117,
  33.315,
  'nicosia'
),
(
  'primeproperty',
  'realestate',
  'images/primeproperty.jpg',
  '+357 25 315300',
  'https://www.prime-property.com/',
  'https://maps.google.com/?q=34.701512,33.0908436',
  $primepropertyen_t$Prime Property Group$primepropertyen_t$,
  $primepropertyen$Prime Property Group is a major full-service real estate company in Limassol, delivering high-end coastal towers, beachfront villas, and luxury residential complexes. They provide 360-degree services covering project development, property management, and residency advisory for international buyers.$primepropertyen$,
  $primepropertyel_t$Prime Property Group$primepropertyel_t$,
  $primepropertyel$Η Prime Property Group είναι μια κορυφαία εταιρεία ανάπτυξης ακινήτων στη Λεμεσό, παραδίδοντας παραθαλάσσιους πύργους, πολυτελείς βίλες και σύγχρονα οικιστικά συγκροτήματα. Προσφέρει ολοκληρωμένες υπηρεσίες κατασκευής, διαχείρισης ακινήτων και επενδυτικής καθοδήγησης για διεθνείς πελάτες.$primepropertyel$,
  $primepropertyru_t$Prime Property Group$primepropertyru_t$,
  $primepropertyru$Prime Property Group — крупный девелопер полного цикла в Лимассоле, возводящий элитные прибрежные высотки, виллы у моря и престижные жилые комплексы. Компания предоставляет комплексные услуги: от строительства и управления недвижимостью до содействия в оформлении ВНЖ.$primepropertyru$,
  $primepropertyzh_t$Prime Property Group$primepropertyzh_t$,
  $primepropertyzh$Prime Property Group 是利马索尔一家大型全方位房地产公司，致力于开发高端海岸大楼、海滨别墅和奢华住宅区。他们提供涵盖项目开发、物业管理和居留咨询的一站式服务，深得国际买家青睐。$primepropertyzh$,
  null,
  false,
  34.701512,
  33.0908436,
  'limassol'
),
(
  'dta',
  'realestate',
  'images/dta.jpg',
  '+357 8000 8383',
  'https://dtagroup.com/',
  'https://maps.google.com/?q=34.6977175,33.090854',
  $dtaen_t$DTA Group$dtaen_t$,
  $dtaen$DTA Group is a distinguished developer renowned for pioneering avant-garde architecture along the Limassol seafront. Their portfolio includes high-rise luxury towers, exclusive private residences, and renovation projects that merge cutting-edge technology with sustainable engineering.$dtaen$,
  $dtael_t$DTA Group$dtael_t$,
  $dtael$Ο Όμιλος DTA είναι ένας διακεκριμένος developer γνωστός για την πρωτοποριακή αρχιτεκτονική του στο παραλιακό μέτωπο της Λεμεσού. Το χαρτοφυλάκιό του περιλαμβάνει πολυτελείς πύργους, ιδιωτικές επαύλεις και έργα που συνδυάζουν τεχνολογία αιχμής με βιώσιμη δόμηση.$dtael$,
  $dtaru_t$DTA Group$dtaru_t$,
  $dtaru$DTA Group — выдающийся девелопер, известный своей авангардной архитектурой на побережье Лимассола. Портфолио компании включает элитные башни, частные резиденции и проекты, сочетающие передовые технологии с экологичным строительством.$dtaru$,
  $dtazh_t$DTA Group$dtazh_t$,
  $dtazh$DTA Group 是一家享有盛誉的开发商，以在利马索尔海滨打造前沿先锋建筑而闻名。其项目组合涵盖高层豪宅大厦、独家私人别墅以及将尖端科技与绿色工程完美融合的开发项目。$dtazh$,
  null,
  false,
  34.6977175,
  33.090854,
  'limassol'
),
(
  'qualitygroup',
  'realestate',
  'images/qualitygroup.jpg',
  null,
  'https://www.qualitygroupcyprus.com/',
  'https://maps.google.com/?q=34.685,33.045',
  $qualitygroupen_t$Quality Group (Limassol Division)$qualitygroupen_t$,
  $qualitygroupen$Recognized across the island, Quality Group brings decades of development prestige to Limassol with visionary boutique apartments, commercial centers, and hospitality-linked residences designed to elevate contemporary urban living.$qualitygroupen$,
  $qualitygroupel_t$Quality Group (Λεμεσός)$qualitygroupel_t$,
  $qualitygroupel$Με αναγνωρισμένη πορεία σε όλο το νησί, η Quality Group διαθέτει ισχυρή παρουσία στη Λεμεσό με μοντέρνα boutique διαμερίσματα, εμπορικά ακίνητα και οικιστικά έργα υψηλών προδιαγραφών που αναβαθμίζουν τη σύγχρονη ζωή στην πόλη.$qualitygroupel$,
  $qualitygroupru_t$Quality Group (Лимассол)$qualitygroupru_t$,
  $qualitygroupru$Компания Quality Group с десятилетиями успешного опыта на Кипре активно реализует в Лимассоле концептуальные бутик-апартаменты, коммерческие центры и жилые комплексы отельного типа, повышающие стандарты комфорта.$qualitygroupru$,
  $qualitygroupzh_t$Quality Group（利马索尔）$qualitygroupzh_t$,
  $qualitygroupzh$Quality Group 在塞浦路斯享负盛名，凭借数十年经验在利马索尔打造了极具前瞻性的精品公寓、商业中心以及酒店式住宅，全面提升当代都市生活品质。$qualitygroupzh$,
  null,
  false,
  34.685,
  33.045,
  'limassol'
),
(
  'occonstruction',
  'realestate',
  'images/occonstruction.jpg',
  null,
  null,
  'https://maps.google.com/?q=34.8905288,33.6381178',
  $occonstructionen_t$O&C Construction$occonstructionen_t$,
  $occonstructionen$O&C Construction is a premier developer in Larnaca, famous for delivering stylish residential projects, seafront residences, and luxury apartments around Mackenzie and the new Marina district with superior craftmanship.$occonstructionen$,
  $occonstructionel_t$O&C Construction$occonstructionel_t$,
  $occonstructionel$Η O&C Construction είναι μια κορυφαία κατασκευαστική εταιρεία στη Λάρνακα, γνωστή για μοντέρνα οικιστικά έργα, παραθαλάσσιες κατοικίες και πολυτελή διαμερίσματα γύρω από το Μακένζι και τη νέα Μαρίνα, με άριστη ποιότητα κατασκευής.$occonstructionel$,
  $occonstructionru_t$O&C Construction$occonstructionru_t$,
  $occonstructionru$O&C Construction — ведущий застройщик в Ларнаке, специализирующийся на стильных жилых проектах, прибрежных апартаментах в районе Маккензи и комплексах возле новой Марины с безупречным качеством отделки.$occonstructionru$,
  $occonstructionzh_t$O&C Construction$occonstructionzh_t$,
  $occonstructionzh$O&C Construction 是拉纳卡首屈一指的开发商，以在麦肯齐 (Mackenzie) 和新码头区周边打造时尚住宅项目、海滨居所和豪华公寓而著称，施工品质无可挑剔。$occonstructionzh$,
  null,
  false,
  34.8905288,
  33.6381178,
  'larnaca'
),
(
  'africanos',
  'realestate',
  'images/africanos.jpg',
  '+357 24 828161',
  'https://africanosproperties.com/',
  'https://maps.google.com/?q=34.9225,33.629',
  $africanosen_t$Africanos Property Developers$africanosen_t$,
  $africanosen$Africanos Property Developers is an established family-founded firm with over two decades of dominance in Larnaca. They specialize in modern, centrally located residential apartment blocks known for timely completion and strong investment returns.$africanosen$,
  $africanosel_t$Africanos Property Developers$africanosel_t$,
  $africanosel$Η Africanos Property Developers είναι μια καθιερωμένη εταιρεία με πάνω από είκοσι χρόνια πρωταγωνιστικής παρουσίας στη Λάρνακα. Ειδικεύεται σε σύγχρονα, κεντρικά κτίρια διαμερισμάτων με έμφαση στην έγκαιρη παράδοση και τις υψηλές αποδόσεις.$africanosel$,
  $africanosru_t$Africanos Property Developers$africanosru_t$,
  $africanosru$Africanos Property Developers — авторитетная компания с более чем двадцатилетним опытом работы в Ларнаке. Она специализируется на современных жилых зданиях в центральных районах города, гарантируя своевременную сдачу и выгодную доходность.$africanosru$,
  $africanoszh_t$Africanos Property Developers$africanoszh_t$,
  $africanoszh$Africanos Property Developers 是一家成熟的开发公司，在拉纳卡深耕二十余年。他们专注于在市中心黄金地段开发现代公寓楼，以按时交付和极高的投资回报率闻名。$africanoszh$,
  null,
  false,
  34.9225,
  33.629,
  'larnaca'
),
(
  'plusproperties',
  'realestate',
  'images/plusproperties.jpg',
  '+357 24 642464',
  'https://www.pluspropertiescyprus.com/',
  'https://maps.google.com/?q=34.9163,33.6378',
  $pluspropertiesen_t$Plus Properties Cyprus$pluspropertiesen_t$,
  $pluspropertiesen$Plus Properties develops high-yield, design-forward residences and premium apartment complexes throughout Larnaca's booming coastal and tourist corridors, bringing international design principles to the local market.$pluspropertiesen$,
  $pluspropertiesel_t$Plus Properties Cyprus$pluspropertiesel_t$,
  $pluspropertiesel$Η Plus Properties αναπτύσσει σύγχρονα οικιστικά συγκροτήματα υψηλής απόδοσης και αισθητικής κατά μήκος των αναπτυσσόμενων παραλιακών και τουριστικών περιοχών της Λάρνακας, προσφέροντας διεθνή πρότυπα σχεδιασμού.$pluspropertiesel$,
  $pluspropertiesru_t$Plus Properties Cyprus$pluspropertiesru_t$,
  $pluspropertiesru$Plus Properties разрабатывает высокодоходные дизайнерские жилые комплексы премиум-класса вдоль активно развивающихся прибрежных и туристических районов Ларнаки, внедряя международные стандарты архитектуры.$pluspropertiesru$,
  $pluspropertieszh_t$Plus Properties Cyprus$pluspropertieszh_t$,
  $pluspropertieszh$Plus Properties 在拉纳卡蓬勃发展的沿海和旅游黄金地段开发高回报、极富设计感的优质公寓群，将国际化建筑理念带入当地市场。$pluspropertieszh$,
  null,
  false,
  34.9163,
  33.6378,
  'larnaca'
),
(
  'karmadevelopers',
  'realestate',
  'images/karmadevelopers.jpg',
  '+357 23 730777',
  'https://karmadevelopers.com/',
  'https://maps.google.com/?q=34.756,32.4165',
  $karmadevelopersen_t$Karma Developers$karmadevelopersen_t$,
  $karmadevelopersen$Karma Developers stands out for creating elegant boutique residences, coastal villas, and bespoke homes in Paphos and Polis Chrysochous, balancing serene Mediterranean lifestyles with cutting-edge architectural finishes.$karmadevelopersen$,
  $karmadevelopersel_t$Karma Developers$karmadevelopersel_t$,
  $karmadevelopersel$Η Karma Developers ξεχωρίζει για τη δημιουργία κομψών boutique κατοικιών, παραθαλάσσιων βιλών και εξατομικευμένων σπιτιών στην Πάφο και την Πόλη Χρυσοχούς, συνδυάζοντας τη μεσογειακή γαλήνη με άρτια αρχιτεκτονική.$karmadevelopersel$,
  $karmadevelopersru_t$Karma Developers$karmadevelopersru_t$,
  $karmadevelopersru$Karma Developers выделяется созданием элегантных бутик-резиденций, прибрежных вилл и домов по индивидуальным проектам в Пафосе и Полисе, гармонично сочетая средиземноморский уют с современной архитектурой.$karmadevelopersru$,
  $karmadeveloperszh_t$Karma Developers$karmadeveloperszh_t$,
  $karmadeveloperszh$Karma Developers 在帕福斯和波利斯 (Polis Chrysochous) 打造优雅的精品住宅、海岸别墅和定制房产，将静谧的地中海生活方式与尖端建筑工艺完美结合。$karmadeveloperszh$,
  null,
  false,
  34.756,
  32.4165,
  'paphos'
),
(
  'domenica',
  'realestate',
  'images/domenica.jpg',
  '+357 26 600700',
  'https://www.domenicagroup.com/',
  'https://maps.google.com/?q=34.7607,32.4068',
  $domenicaen_t$Domenica Group$domenicaen_t$,
  $domenicaen$Founded in 1961, Domenica Group is one of the most historic and reliable construction and real estate developers in Paphos, offering luxury sea-view apartments, gated family communities, and tourist complexes.$domenicaen$,
  $domenicael_t$Domenica Group$domenicael_t$,
  $domenicael$Ιδρυμένη το 1961, η Domenica Group είναι ένας από τους πιο ιστορικούς και αξιόπιστους ομίλους ανάπτυξης γης στην Πάφο, με πολυτελή διαμερίσματα με θέα στη θάλασσα, κλειστές οικιστικές κοινότητες και τουριστικά θέρετρα.$domenicael$,
  $domenicaru_t$Domenica Group$domenicaru_t$,
  $domenicaru$Основанная в 1961 году, Domenica Group является одним из старейших и наиболее надежных застройщиков в Пафосе, предлагая роскошные апартаменты с видом на море, закрытые семейные поселки и курортные объекты.$domenicaru$,
  $domenicazh_t$Domenica Group$domenicazh_t$,
  $domenicazh$Domenica Group 成立于 1961 年，是帕福斯历史最悠久、最值得信赖的房地产开发集团之一，提供海景豪华公寓、封闭式家庭社区和度假设施。$domenicazh$,
  null,
  false,
  34.7607,
  32.4068,
  'paphos'
),
(
  'giovanihomes',
  'realestate',
  'images/giovanihomes.jpg',
  '+357 23 833780',
  'https://www.giovani.com.cy/',
  'https://maps.google.com/?q=34.748,32.428',
  $giovanihomesen_t$Giovani Homes (Paphos Projects)$giovanihomesen_t$,
  $giovanihomesen$Giovani Homes brings its renowned engineering pedigree to premium Paphos locations, delivering high-end villa developments and luxury coastal residences crafted for refined living and Golden Visa property investors.$giovanihomesen$,
  $giovanihomesel_t$Giovani Homes (Πάφος)$giovanihomesel_t$,
  $giovanihomesel$Η Giovani Homes επεκτείνει την κατασκευαστική της εμπειρία σε προνομιούχες τοποθεσίες της Πάφου, παραδίδοντας πολυτελείς βίλες και παραθαλάσσιες κατοικίες ιδανικές για εκλεπτυσμένη διαβίωση και επενδυτικά προγράμματα.$giovanihomesel$,
  $giovanihomesru_t$Giovani Homes (Пафос)$giovanihomesru_t$,
  $giovanihomesru$Giovani Homes реализует первоклассные проекты в Пафосе, создавая элитные виллы и прибрежные резиденции, созданные для комфортной жизни и участия в инвестиционных программах получения ВНЖ.$giovanihomesru$,
  $giovanihomeszh_t$Giovani Homes（帕福斯）$giovanihomeszh_t$,
  $giovanihomeszh$Giovani Homes 将其卓越的建筑品质拓展至帕福斯黄金地段，交付高端别墅社区和海滨豪宅，专为追求精致生活与居留投资的高净值人士打造。$giovanihomeszh$,
  null,
  false,
  34.748,
  32.428,
  'paphos'
),
(
  'giovanigroup',
  'realestate',
  'images/giovanigroup.jpg',
  '+357 23 833780',
  'https://www.giovani.com.cy/',
  'https://maps.google.com/?q=35.0201,33.9859',
  $giovanigroupen_t$Giovani Group$giovanigroupen_t$,
  $giovanigroupen$As the undisputed market leader in the Famagusta district, Giovani Group has developed hundreds of premier luxury villas, modern beachfront projects, and signature gated communities across Ayia Napa and Protaras.$giovanigroupen$,
  $giovanigroupel_t$Giovani Group$giovanigroupel_t$,
  $giovanigroupel$Ως ο αδιαμφισβήτητος ηγέτης στην επαρχία Αμμοχώστου, ο Όμιλος Giovani έχει αναπτύξει εκατοντάδες πολυτελείς βίλες, σύγχρονα παραθαλάσσια έργα και φυλασσόμενα οικιστικά συγκροτήματα σε Αγία Νάπα και Πρωταρά.$giovanigroupel$,
  $giovanigroupru_t$Giovani Group$giovanigroupru_t$,
  $giovanigroupru$Безоговорочный лидер рынка недвижимости в регионе Фамагусты, Giovani Group построила сотни элитных вилл, современных прибрежных проектов и закрытых комплексов в Айя-Напе и Протарасе.$giovanigroupru$,
  $giovanigroupzh_t$Giovani Group$giovanigroupzh_t$,
  $giovanigroupzh$作为法马古斯塔地区无可争议的市场领导者，Giovani Group 在圣纳帕和普罗塔拉斯开发了数百栋顶级豪华别墅、现代海滨项目以及封闭式住宅社区。$giovanigroupzh$,
  null,
  false,
  35.0201,
  33.9859,
  'famagusta'
),
(
  'karmagroup',
  'realestate',
  'images/karmagroup.jpg',
  '+357 23 730777',
  'https://karmadevelopers.com/',
  'https://maps.google.com/?q=35.0528895,34.0113793',
  $karmagroupen_t$Karma Group (Famagusta Division)$karmagroupen_t$,
  $karmagroupen$Karma Group is widely acclaimed in Protaras and Ayia Napa for creating eco-conscious holiday homes, boutique sea-view apartments, and luxury villas steps away from blue-flag beaches.$karmagroupen$,
  $karmagroupel_t$Karma Group (Αμμόχωστος)$karmagroupel_t$,
  $karmagroupel$Ο Όμιλος Karma χαίρει μεγάλης εκτίμησης σε Πρωταρά και Αγία Νάπα για τη δημιουργία οικολογικών εξοχικών κατοικιών, boutique διαμερισμάτων με θέα στη θάλασσα και πολυτελών βιλών δίπλα σε βραβευμένες παραλίες.$karmagroupel$,
  $karmagroupru_t$Karma Group (Фамагуста)$karmagroupru_t$,
  $karmagroupru$Karma Group пользуется высоким признанием в Протарасе и Айя-Напе благодаря созданию экологичных домов для отдыха, бутик-апартаментов с видом на море и роскошных вилл рядом с лучшими пляжами.$karmagroupru$,
  $karmagroupzh_t$Karma Group（法马古斯塔）$karmagroupzh_t$,
  $karmagroupzh$Karma Group 在普罗塔拉斯和圣纳帕广受赞誉，致力于在蓝旗沙滩旁打造环保度假屋、精品海景公寓和豪华私人别墅。$karmagroupzh$,
  null,
  false,
  35.0528895,
  34.0113793,
  'famagusta'
),
(
  'skyprime',
  'realestate',
  'images/skyprime.jpg',
  '+357 23 722026',
  'https://www.skyprimegroup.com/',
  'https://maps.google.com/?q=34.9889204,33.9814395',
  $skyprimeen_t$SkyPrime Group$skyprimeen_t$,
  $skyprimeen$Specializing in ultra-luxury bespoke developments in Ayia Napa and Cape Greco, SkyPrime Group designs iconic seafront villas that feature private infinity pools, smart home automation, and five-star concierge living.$skyprimeen$,
  $skyprimeel_t$SkyPrime Group$skyprimeel_t$,
  $skyprimeel$Με εξειδίκευση σε υπερπολυτελή έργα στην Αγία Νάπα και το Κάβο Γκρέκο, η SkyPrime Group κατασκευάζει εμβληματικές παραθαλάσσιες βίλες με ιδιωτικές πισίνες υπερχείλισης, smart home αυτοματισμούς και υπηρεσίες concierge.$skyprimeel$,
  $skyprimeru_t$SkyPrime Group$skyprimeru_t$,
  $skyprimeru$Специализируясь на эксклюзивной ультра-роскошной недвижимости в Айя-Напе и на мысе Греко, SkyPrime Group проектирует знаковые виллы у моря с инфинити-бассейнами, системами «умный дом» и пятизвездочным сервисом.$skyprimeru$,
  $skyprimezh_t$SkyPrime Group$skyprimezh_t$,
  $skyprimezh$SkyPrime Group 专精于圣纳帕和格雷科角 (Cape Greco) 的超级奢华定制开发，设计带有私人无边泳池、智能家居系统和五星级管家服务的地标性海滨别墅。$skyprimezh$,
  null,
  false,
  34.9889204,
  33.9814395,
  'famagusta'
)
on conflict (id) do update set
  category = excluded.category,
  image_url = excluded.image_url,
  phone = excluded.phone,
  website = excluded.website,
  map_link = excluded.map_link,
  title_en = excluded.title_en,
  desc_en = excluded.desc_en,
  title_el = excluded.title_el,
  desc_el = excluded.desc_el,
  title_ru = excluded.title_ru,
  desc_ru = excluded.desc_ru,
  title_zh = excluded.title_zh,
  desc_zh = excluded.desc_zh,
  subcategory = excluded.subcategory,
  lat = excluded.lat,
  lng = excluded.lng,
  town = excluded.town;
