insert into public.places (
  id, category, image_url, phone, website, map_link,
  title_en, desc_en, title_el, desc_el, title_ru, desc_ru, title_zh, desc_zh,
  subcategory, is_best_of_month, lat, lng, town
) values
(
  'neocleous', 'services', 'images/neocleous.jpg', '+357 25 110 000', 'https://www.neocleous.com/',
  'https://maps.google.com/?q=34.6874234,33.0494405',
  'Andreas Neocleous & Co LLC',
  'Headquartered in Limassol, this is one of the largest and most prestigious law firms in Cyprus. It offers top-tier legal representation in corporate, commercial, and shipping law, providing unmatched expertise for international and local clients.',
  'Andreas Neocleous & Co LLC',
  'Με έδρα τη Λεμεσό, πρόκειται για ένα από τα μεγαλύτερα και πιο αναγνωρισμένα δικηγορικά γραφεία στην Κύπρο. Προσφέρει κορυφαία νομική εκπροσώπηση στο εταιρικό, εμπορικό και ναυτιλιακό δίκαιο, παρέχοντας απαράμιλλη τεχνογνωσία σε διεθνείς και τοπικούς πελάτες.',
  'Andreas Neocleous & Co LLC',
  'Штаб-квартира этой компании, одной из крупнейших и наиболее престижных юридических фирм на Кипре, находится в Лимассоле. Фирма предлагает первоклассное юридическое представительство в области корпоративного, коммерческого и морского права.',
  'Andreas Neocleous & Co LLC',
  '总部位于利马索尔，这是塞浦路斯最大、最负盛名的律师事务所之一。它在公司法、商法和海事法方面提供顶级的法律代表服务，为国际和本地客户提供无与伦比的专业知识。',
  'law', false, 34.6874234, 33.0494405, 'limassol'
),
(
  'demetriades', 'services', 'images/demetriades.jpg', '+357 25 800 000', 'https://demetriades.com/',
  'https://maps.google.com/?q=34.6817536,33.0479732',
  'Chrysses Demetriades & Co LLC',
  'Established in Limassol, it is a highly respected law firm with decades of experience, particularly renowned for its maritime law practice, tax, and dispute resolution. It is a trusted partner for global corporations operating in Cyprus.',
  'Chrysses Demetriades & Co LLC',
  'Με μακρόχρονη παρουσία στη Λεμεσό, είναι ένα εξαιρετικά αξιόπιστο δικηγορικό γραφείο, ιδιαίτερα γνωστό για την εξειδίκευσή του στο ναυτιλιακό δίκαιο, τα φορολογικά και την επίλυση διαφορών. Αποτελεί στρατηγικό συνεργάτη για πολυεθνικές εταιρείες.',
  'Chrysses Demetriades & Co LLC',
  'Основанная в Лимассоле, это уважаемая юридическая фирма с многолетним опытом, особенно известная своей практикой в области морского права, налогообложения и разрешения споров.',
  'Chrysses Demetriades & Co LLC',
  '成立于利马索尔，这是一家备受尊敬的律师事务所，拥有数十年的经验，尤其以其海事法、税务和争议解决业务而闻名。它是跨国公司值得信赖的合作伙伴。',
  'law', false, 34.6817536, 33.0479732, 'limassol'
),
(
  'kyprianou', 'services', 'images/kyprianou.svg', '+357 25 363 685', 'https://www.kyprianou.com/',
  'https://maps.google.com/?q=34.6827382,33.0476076',
  'Michael Kyprianou & Co LLC',
  'With a strong presence in Limassol, this award-winning law firm provides comprehensive legal services encompassing real estate, immigration, and corporate litigation. Their dedicated team ensures personalized and effective legal solutions.',
  'Michael Kyprianou & Co LLC',
  'Με ισχυρή παρουσία στη Λεμεσό, αυτό το πολυβραβευμένο δικηγορικό γραφείο παρέχει ολοκληρωμένες νομικές υπηρεσίες που καλύπτουν τα ακίνητα, τη μετανάστευση και τις εταιρικές διαφορές. Η έμπειρη ομάδα τους εξασφαλίζει εξατομικευμένες λύσεις.',
  'Michael Kyprianou & Co LLC',
  'Эта отмеченная наградами юридическая фирма с сильным присутствием в Лимассоле предоставляет комплексные юридические услуги, включая недвижимость, иммиграцию и корпоративные споры.',
  'Michael Kyprianou & Co LLC',
  '凭借在利马索尔的强大影响力，这家屡获殊荣的律师事务所提供全面的法律服务，包括房地产、移民和公司诉讼。他们敬业的团队确保提供个性化且有效的法律解决方案。',
  'law', false, 34.6827382, 33.0476076, 'limassol'
),
(
  'vakis', 'services', 'images/vakis.jpg', '+357 25 369 765', 'https://www.vakisassociates.com/',
  'https://maps.google.com/?q=34.6763502,33.0474526',
  'Vakis Associates',
  'Vakis Associates is a premier architectural and interior design studio in Limassol, known for creating luxurious, contemporary residential spaces and exclusive hospitality projects that harmonize with the Mediterranean environment.',
  'Vakis Associates',
  'Η Vakis Associates είναι ένα κορυφαίο αρχιτεκτονικό γραφείο στη Λεμεσό, γνωστό για τη δημιουργία πολυτελών, σύγχρονων οικιστικών χώρων και έργων φιλοξενίας που εναρμονίζονται απόλυτα με το μεσογειακό περιβάλλον.',
  'Vakis Associates',
  'Vakis Associates — это первоклассная студия архитектуры и дизайна интерьеров в Лимассоле, известная созданием роскошных современных жилых пространств и эксклюзивных гостиничных проектов.',
  'Vakis Associates',
  'Vakis Associates 是利马索尔首屈一指的建筑和室内设计工作室，以创造与地中海环境相协调的豪华现代住宅空间和独特酒店项目而闻名。',
  'architects', false, 34.6763502, 33.0474526, 'limassol'
),
(
  'armeftis', 'services', 'images/armeftis.jpg', '+357 25 828 280', 'https://armeftis.com/',
  'https://maps.google.com/?q=34.6775595,33.0473243',
  'Armeftis Partners',
  'Founded in Limassol, Armeftis Partners focuses on innovative urban design and sustainable architecture. Their impressive portfolio includes modern commercial high-rises and state-of-the-art public spaces that shape the city''s future skyline.',
  'Armeftis Partners',
  'Με έδρα τη Λεμεσό, η Armeftis Partners εστιάζει στον καινοτόμο αστικό σχεδιασμό και τη βιώσιμη αρχιτεκτονική. Το εντυπωσιακό χαρτοφυλάκιό της περιλαμβάνει σύγχρονους εμπορικούς πύργους που διαμορφώνουν τον ορίζοντα της πόλης.',
  'Armeftis Partners',
  'Основанная в Лимассоле, компания Armeftis Partners специализируется на инновационном городском дизайне и устойчивой архитектуре. Их впечатляющее портфолио включает современные коммерческие небоскребы.',
  'Armeftis Partners',
  'Armeftis Partners 成立于利马索尔，专注于创新的城市设计和可持续建筑。其令人印象深刻的作品集包括塑造城市未来天际线的现代商业高层建筑。',
  'architects', false, 34.6775595, 33.0473243, 'limassol'
),
(
  'kythreotis', 'services', 'images/kythreotis.jpg', '+357 22 447 766', 'https://kythreotisarchitects.llc/',
  'https://maps.google.com/?q=35.1627446,33.3612743',
  'Kythreotis Architects',
  'Kythreotis Architects is an acclaimed Nicosia-based firm celebrated for its minimalist aesthetic and functional elegance. They specialize in high-end private villas, boutique corporate offices, and cutting-edge cultural buildings.',
  'Kythreotis Architects',
  'Το γραφείο Kythreotis Architects στη Λευκωσία φημίζεται για τη μινιμαλιστική αισθητική και τη λειτουργική του κομψότητα. Εξειδικεύεται σε πολυτελείς ιδιωτικές βίλες, σύγχρονα εταιρικά γραφεία και πολιτιστικά κτίρια αιχμής.',
  'Kythreotis Architects',
  'Kythreotis Architects — известная фирма из Никосии, славящаяся своей минималистской эстетикой и функциональной элегантностью. Они специализируются на элитных частных виллах и корпоративных офисах.',
  'Kythreotis Architects',
  'Kythreotis Architects 是一家位于尼科西亚的著名公司，以其极简主义美学和功能性优雅而闻名。他们专注于高端私人别墅、精品企业办公室和尖端文化建筑。',
  'architects', false, 35.1627446, 33.3612743, 'nicosia'
),
(
  'deloitte', 'services', 'images/deloitte.jpg', '+357 25 868 686', 'https://www.deloitte.com/cy/en.html',
  'https://maps.google.com/?q=34.6868594,33.0546416',
  'Deloitte Cyprus (Limassol Office)',
  'The Limassol branch of Deloitte offers world-class audit, tax, consulting, and financial advisory services. They support multinational corporations, shipping firms, and local enterprises with industry-leading insights and strict compliance.',
  'Deloitte Cyprus (Limassol Office)',
  'Το παράρτημα της Deloitte στη Λεμεσό προσφέρει υπηρεσίες ελέγχου, φορολογίας και χρηματοοικονομικών συμβουλών παγκόσμιας κλάσης. Υποστηρίζουν πολυεθνικές, ναυτιλιακές εταιρείες και τοπικές επιχειρήσεις με κορυφαία τεχνογνωσία.',
  'Deloitte Cyprus (Limassol Office)',
  'Филиал Deloitte в Лимассоле предлагает услуги мирового класса в области аудита, налогообложения, консалтинга и финансовых консультаций, поддерживая транснациональные и местные компании.',
  'Deloitte Cyprus (Limassol Office)',
  '德勤 (Deloitte) 利马索尔分公司提供世界级的审计、税务、咨询和财务顾问服务。他们凭借行业领先的洞察力支持跨国公司、航运公司和本地企业。',
  'accounting', false, 34.6868594, 33.0546416, 'limassol'
),
(
  'bakertilly', 'services', 'images/bakertilly.jpg', '+357 25 591 515', 'https://bakertillysee.com/',
  'https://maps.google.com/?q=34.6790599,33.0512202',
  'Baker Tilly Cyprus (Limassol Office)',
  'Baker Tilly''s Limassol office is highly regarded for its bespoke accounting, risk management, and corporate advisory services. They provide expert financial solutions tailored to the needs of international investors and local entrepreneurs alike.',
  'Baker Tilly Cyprus (Limassol Office)',
  'Το γραφείο της Baker Tilly στη Λεμεσό χαίρει μεγάλης εκτίμησης για τις εξατομικευμένες λογιστικές υπηρεσίες και τη διαχείριση κινδύνων. Προσφέρουν εξειδικευμένες οικονομικές λύσεις για διεθνείς επενδυτές και ντόπιους επιχειρηματίες.',
  'Baker Tilly Cyprus (Limassol Office)',
  'Офис Baker Tilly в Лимассоле высоко ценится за индивидуальные бухгалтерские услуги, управление рисками и корпоративное консультирование.',
  'Baker Tilly Cyprus (Limassol Office)',
  '贝克蒂利 (Baker Tilly) 利马索尔办事处因其定制的会计、风险管理和企业咨询服务而备受赞誉，为国际投资者提供专业的财务解决方案。',
  'accounting', false, 34.6790599, 33.0512202, 'limassol'
),
(
  'krestonproios', 'services', 'images/krestonproios.jpg', '+357 22 490 094', 'https://krestonproios.com/',
  'https://maps.google.com/?q=35.1570648,33.3582542',
  'Kreston Proios',
  'Kreston Proios is a leading independent accounting and advisory firm in Nicosia. Known for its personalized approach, the firm excels in tax planning, wealth management, and corporate structuring for high-net-worth individuals and dynamic businesses.',
  'Kreston Proios',
  'Η Kreston Proios είναι μια κορυφαία ανεξάρτητη λογιστική και συμβουλευτική εταιρεία στη Λευκωσία. Γνωστή για την εξατομικευμένη της προσέγγιση, αριστεύει στον φορολογικό σχεδιασμό και την εταιρική δόμηση για δυναμικές επιχειρήσεις.',
  'Kreston Proios',
  'Kreston Proios — ведущая независимая бухгалтерская и консалтинговая фирма в Никосии, известная своим индивидуальным подходом в налоговом планировании и управлении капиталом.',
  'Kreston Proios',
  'Kreston Proios 是尼科西亚一家领先的独立会计和咨询公司。该公司以其个性化的服务而闻名，擅长高净值人士和动态企业的税务规划和企业架构。',
  'accounting', false, 35.1570648, 33.3582542, 'nicosia'
),
(
  'prestigevip', 'services', 'images/prestigevip.jpg', '+357 25 322 055', 'https://www.prestigecy.com/',
  'https://maps.google.com/?q=34.7070135,33.1169800',
  'Prestige VIP Services',
  'Based in Limassol, Prestige VIP Services is the ultimate luxury concierge provider in Cyprus. From renting luxury supercars and private yachts to providing full-time chauffeurs and bespoke lifestyle experiences, they redefine exclusivity.',
  'Prestige VIP Services',
  'Με έδρα τη Λεμεσό, η Prestige VIP Services είναι ο απόλυτος πάροχος πολυτελών υπηρεσιών concierge στην Κύπρο. Από την ενοικίαση supercars και ιδιωτικών γιοτ μέχρι υπηρεσίες με προσωπικούς σοφέρ, επαναπροσδιορίζουν την αποκλειστικότητα.',
  'Prestige VIP Services',
  'Базирующаяся в Лимассоле, Prestige VIP Services является ведущим поставщиком элитных консьерж-услуг на Кипре. От аренды суперкаров и яхт до услуг личного водителя, они предлагают непревзойденный уровень эксклюзивности.',
  'Prestige VIP Services',
  'Prestige VIP Services 总部位于利马索尔，是塞浦路斯终极的豪华礼宾服务提供商。从租赁豪华超级跑车和私人游艇，到安排私人司机，他们重新定义了尊贵体验。',
  'transfer', false, 34.7070135, 33.1169800, 'limassol'
),
(
  'columbiablue', 'services', 'images/columbiablue.jpg', '+357 25 843 100', 'https://columbia.blue/',
  'https://maps.google.com/?q=34.7026400,33.0781583',
  'COLUMBIA blue',
  'Part of the renowned Columbia Group, COLUMBIA blue offers premium lifestyle management and elite travel arrangements. Operating from Limassol, they secure reservations at top-tier restaurants, arrange private aviation, and ensure a seamless luxury experience.',
  'COLUMBIA blue',
  'Μέρος του φημισμένου Ομίλου Columbia, η COLUMBIA blue προσφέρει κορυφαία διαχείριση lifestyle και ελίτ ταξιδιωτικές διευθετήσεις από τη Λεμεσό, εξασφαλίζοντας κρατήσεις σε κορυφαία εστιατόρια και ιδιωτικές πτήσεις.',
  'COLUMBIA blue',
  'Эта служба, являющаяся частью известной группы Columbia, предлагает первоклассное управление стилем жизни и элитную организацию путешествий из Лимассола.',
  'COLUMBIA blue',
  '作为著名的 Columbia Group 的一部分，COLUMBIA blue 提供高级生活方式管理和精英旅行安排。他们从利马索尔运营，确保为您带来无缝的奢华体验。',
  'transfer', false, 34.7026400, 33.0781583, 'limassol'
),
(
  'asg', 'services', 'images/asg.webp', '+357 25 880 100', 'https://www.asg.cy/',
  'https://maps.google.com/?q=34.6562319,32.9965306',
  'Andy Spyrou Group (ASG)',
  'Andy Spyrou Group (ASG), based at 86 Franklin Roosevelt Avenue in Limassol, is Cyprus''s leading mobility company. Through Europcar Cyprus, ASG Leasing and a modern fleet, they provide car rental, corporate fleet and business transport across the island.',
  'Andy Spyrou Group (ASG)',
  'Ο Όμιλος Andy Spyrou (ASG), με έδρα τη Λεωφόρο Φραγκλίνου Ρούσβελτ 86 στη Λεμεσό, είναι ο κορυφαίος όμιλος κινητικότητας στην Κύπρο. Μέσω της Europcar Cyprus, της ASG Leasing και ενός σύγχρονου στόλου, προσφέρει ενοικίαση αυτοκινήτων, εταιρικό στόλο και επαγγελματικές μετακινήσεις σε όλο το νησί.',
  'Andy Spyrou Group (ASG)',
  'Andy Spyrou Group (ASG) с офисом на проспекте Франклина Рузвельта, 86 в Лимассоле — ведущая компания мобильности на Кипре. Через Europcar Cyprus, ASG Leasing и современный автопарк она предоставляет аренду автомобилей, корпоративный флот и деловые перевозки по всему острову.',
  'Andy Spyrou Group (ASG)',
  'Andy Spyrou Group (ASG) 总部位于利马索尔富兰克林·罗斯福大道 86 号，是塞浦路斯领先的出行集团。通过 Europcar Cyprus、ASG Leasing 和现代化车队，他们提供全岛的汽车租赁、企业车队和商务交通服务。',
  'transfer', false, 34.6562319, 32.9965306, 'limassol'
)
on conflict (id) do update set
  category = excluded.category,
  image_url = excluded.image_url,
  phone = excluded.phone,
  website = excluded.website,
  map_link = excluded.map_link,
  title_en = excluded.title_en,
  desc_en = excluded.desc_en,
  title_el = excluded.title_el,
  desc_el = excluded.desc_el,
  title_ru = excluded.title_ru,
  desc_ru = excluded.desc_ru,
  title_zh = excluded.title_zh,
  desc_zh = excluded.desc_zh,
  subcategory = excluded.subcategory,
  is_best_of_month = excluded.is_best_of_month,
  lat = excluded.lat,
  lng = excluded.lng,
  town = excluded.town;
