delete from public.places where id in ('cyprusmuseum', 'liopetri', 'dodekapente', 'omodos', 'troodosjeep', 'duomo', 'musecafe');

update public.places
set town = 'famagusta'
where lower(coalesce(town, '')) in ('ayia_napa', 'protaras', 'paralimni', 'ammochostos');

update public.places
set town = case
  when lng >= 33.75 then 'famagusta'
  when lat >= 35.05 and lng >= 33.15 and lng < 33.55 then 'nicosia'
  when lng < 32.72 then 'paphos'
  when lng < 33.25 then 'limassol'
  else 'larnaca'
end
where lower(coalesce(town, '')) in ('other', '') or town is null;

insert into public.places (
  id, category, image_url, phone, website, map_link,
  title_en, desc_en, title_el, desc_el, title_ru, desc_ru, title_zh, desc_zh,
  subcategory, is_best_of_month, lat, lng, town
) values
(
  'tocayo',
  'restaurants',
  'images/tocayo.jpg',
  '+357 22 100800',
  'https://tocayo.com.cy/',
  'https://maps.google.com/?q=35.1694,33.3618',
  $tocayoen_t$Tocayo$tocayoen_t$,
  $tocayoen$Located in the heart of Nicosia, Tocayo offers a chic, minimalist setting and an innovative Asian fusion menu. Known for its exquisite tapas-style dishes, creative cocktails, and vibrant atmosphere, it is the perfect spot for a sophisticated night out in the capital.$tocayoen$,
  $tocayoel_t$Tocayo$tocayoel_t$,
  $tocayoel$Στην καρδιά της Λευκωσίας, το Tocayo προσφέρει ένα κομψό, μινιμαλιστικό περιβάλλον και ένα καινοτόμο μενού ασιατικής fusion κουζίνας. Γνωστό για τα εξαιρετικά πιάτα τύπου τάπας, τα δημιουργικά κοκτέιλ και τη ζωντανή ατμόσφαιρα, είναι το ιδανικό μέρος για μια εκλεπτυσμένη βραδινή έξοδο στην πρωτεύουσα.$tocayoel$,
  $tocayoru_t$Tocayo$tocayoru_t$,
  $tocayoru$Расположенный в самом сердце Никосии, ресторан Tocayo предлагает элегантную минималистичную обстановку и инновационное меню азиатской кухни фьюжн. Известный своими изысканными блюдами в стиле тапас, креативными коктейлями и оживленной атмосферой, это идеальное место для изысканного вечера в столице.$tocayoru$,
  $tocayozh_t$Tocayo$tocayozh_t$,
  $tocayozh$Tocayo 位于尼科西亚市中心，提供别致、极简的环境和创新的亚洲融合菜单。这里以其精致的塔帕斯风格菜肴、创意鸡尾酒和充满活力的氛围而闻名，是首都享受精致夜晚的完美去处。$tocayozh$,
  'asian',
  false,
  35.1694,
  33.3618,
  'nicosia'
),
(
  'dionysusmansion',
  'restaurants',
  'images/dionysusmansion.jpg',
  '+357 25 222210',
  'https://dionysusmansion.com/',
  'https://maps.google.com/?q=34.6756,33.0448',
  $dionysusmansionen_t$Dionysus Mansion$dionysusmansionen_t$,
  $dionysusmansionen$Situated in a beautifully restored historic house in Limassol, Dionysus Mansion elevates traditional Cypriot cuisine with modern culinary techniques. Featuring a stunning, fairy-lit garden for outdoor dining, it provides a magical atmosphere and a menu filled with authentic, localized flavors and premium local wines.$dionysusmansionen$,
  $dionysusmansionel_t$Dionysus Mansion$dionysusmansionel_t$,
  $dionysusmansionel$Στεγασμένο σε ένα όμορφα αναπαλαιωμένο ιστορικό αρχοντικό στη Λεμεσό, το Dionysus Mansion απογειώνει την παραδοσιακή κυπριακή κουζίνα με σύγχρονες γαστρονομικές τεχνικές. Διαθέτοντας έναν μαγευτικό, φωταγωγημένο κήπο για δείπνο σε ανοιχτό χώρο, προσφέρει μια παραμυθένια ατμόσφαιρα και ένα μενού γεμάτο αυθεντικές γεύσεις και κορυφαία τοπικά κρασιά.$dionysusmansionel$,
  $dionysusmansionru_t$Dionysus Mansion$dionysusmansionru_t$,
  $dionysusmansionru$Расположенный в прекрасно отреставрированном историческом особняке в Лимассоле, Dionysus Mansion возвышает традиционную кипрскую кухню с помощью современных кулинарных техник. Потрясающий сад, украшенный гирляндами для ужина на свежем воздухе, создает волшебную атмосферу и предлагает меню, полное аутентичных вкусов и первоклассных местных вин.$dionysusmansionru$,
  $dionysusmansionzh_t$Dionysus Mansion$dionysusmansionzh_t$,
  $dionysusmansionzh$Dionysus Mansion 坐落于利马索尔一栋经过精美修复的历史建筑内，采用现代烹饪技术提升了传统的塞浦路斯美食。这里拥有一个令人惊叹的、灯光闪烁的户外用餐花园，提供神奇的氛围以及充满地道风味和优质当地葡萄酒的菜单。$dionysusmansionzh$,
  'traditional',
  false,
  34.6756,
  33.0448,
  'limassol'
),
(
  'maqamalsultan',
  'restaurants',
  'images/maqamalsultan.jpg',
  '+357 24 628282',
  'https://www.maqamalsultan.com/',
  'https://maps.google.com/?q=34.9163,33.6378',
  $maqamalsultanen_t$Maqam Al Sultan$maqamalsultanen_t$,
  $maqamalsultanen$Set right on the lively Finikoudes promenade in Larnaca, Maqam Al Sultan delivers a highly authentic Lebanese dining experience. Guests can enjoy a rich array of traditional mezzes, perfectly grilled meats, and shisha, all accompanied by spectacular views of the Mediterranean Sea and warm Middle Eastern hospitality.$maqamalsultanen$,
  $maqamalsultanel_t$Maqam Al Sultan$maqamalsultanel_t$,
  $maqamalsultanel$Πάνω στον πολυσύχναστο πεζόδρομο των Φοινικούδων στη Λάρνακα, το Maqam Al Sultan προσφέρει μια εξαιρετικά αυθεντική λιβανέζικη γαστρονομική εμπειρία. Οι επισκέπτες μπορούν να απολαύσουν μια πλούσια ποικιλία από παραδοσιακούς μεζέδες, καλοψημένα κρέατα και ναργιλέ, με εκπληκτική θέα στη Μεσόγειο και ζεστή ανατολίτικη φιλοξενία.$maqamalsultanel$,
  $maqamalsultanru_t$Maqam Al Sultan$maqamalsultanru_t$,
  $maqamalsultanru$Расположенный прямо на оживленной набережной Финикудес в Ларнаке, Maqam Al Sultan предлагает по-настоящему аутентичный опыт ливанской кухни. Гости могут насладиться богатым выбором традиционных мезе, идеально приготовленным на гриле мясом и кальяном в сопровождении захватывающего вида на Средиземное море и теплого ближневосточного гостеприимства.$maqamalsultanru$,
  $maqamalsultanzh_t$Maqam Al Sultan$maqamalsultanzh_t$,
  $maqamalsultanzh$Maqam Al Sultan 坐落于拉纳卡热闹的菲尼库德斯 (Finikoudes) 海滨长廊上，提供极其地道的黎巴嫩餐饮体验。客人可以享用丰富多样的传统小吃 (Meze)、完美的烤肉和水烟，同时欣赏地中海的壮丽景色并感受中东的热情好客。$maqamalsultanzh$,
  'traditional',
  false,
  34.9163,
  33.6378,
  'larnaca'
),
(
  'glasshouse',
  'restaurants',
  'images/glasshouse.jpg',
  '+357 23 724000',
  'https://www.adams.com.cy/',
  'https://maps.google.com/?q=34.9874,33.9597',
  $glasshouseen_t$Glasshouse Lounge Restaurant$glasshouseen_t$,
  $glasshouseen$Perched on the top floor of the Adams Beach Hotel in Ayia Napa, the Glasshouse Lounge offers a spectacular fine-dining experience with panoramic views of Nissi Bay. With its striking glass-themed décor and an innovative international menu, it is the ultimate destination for special occasions and luxury sunset dinners.$glasshouseen$,
  $glasshouseel_t$Glasshouse Lounge Restaurant$glasshouseel_t$,
  $glasshouseel$Στον τελευταίο όροφο του Adams Beach Hotel στην Αγία Νάπα, το Glasshouse Lounge προσφέρει μια θεαματική fine-dining εμπειρία με πανοραμική θέα στον κόλπο του Nissi. Με εντυπωσιακή διακόσμηση από γυαλί και ένα καινοτόμο διεθνές μενού, αποτελεί τον απόλυτο προορισμό για ειδικές περιστάσεις και πολυτελή δείπνα στο ηλιοβασίλεμα.$glasshouseel$,
  $glasshouseru_t$Glasshouse Lounge Restaurant$glasshouseru_t$,
  $glasshouseru$Расположенный на верхнем этаже отеля Adams Beach в Айя-Напе, ресторан Glasshouse Lounge предлагает захватывающие впечатления от высокой кухни с панорамным видом на залив Нисси. Яркий декор в стеклянном стиле и инновационное интернациональное меню делают его идеальным местом для особых случаев и роскошных ужинов на закате.$glasshouseru$,
  $glasshousezh_t$Glasshouse Lounge Restaurant$glasshousezh_t$,
  $glasshousezh$Glasshouse Lounge 坐落于圣纳帕 (Ayia Napa) 亚当斯海滩酒店 (Adams Beach Hotel) 的顶层，提供壮观的高级餐饮体验，可欣赏尼斯湾 (Nissi Bay) 的全景。凭借其引人注目的玻璃主题装饰和创新的国际菜单，它是举办特殊场合和豪华日落晚餐的终极目的地。$glasshousezh$,
  'fine_dining',
  false,
  34.9874,
  33.9597,
  'famagusta'
),
(
  'pyxida',
  'restaurants',
  'images/pyxida.jpg',
  '+357 22 671129',
  'https://www.pyxidafishtavern.com/',
  'https://maps.google.com/?q=35.1698,33.3602',
  $pyxidaen_t$Pyxida Fish Tavern$pyxidaen_t$,
  $pyxidaen$Located in the center of Nicosia, Pyxida is a top-tier seafood restaurant renowned for its fresh fish and elegant atmosphere. From classic fish meze to gourmet seafood pasta, it offers an unforgettable culinary journey for seafood lovers in the capital.$pyxidaen$,
  $pyxidael_t$Pyxida Fish Tavern$pyxidael_t$,
  $pyxidael$Βρίσκεται στο κέντρο της Λευκωσίας, η Pyxida είναι ένα κορυφαίο εστιατόριο θαλασσινών, φημισμένο για τα φρέσκα ψάρια και την κομψή του ατμόσφαιρα. Από τον κλασικό ψαρομεζέ μέχρι τις γκουρμέ μακαρονάδες θαλασσινών, προσφέρει ένα αξέχαστο γαστρονομικό ταξίδι στην πρωτεύουσα.$pyxidael$,
  $pyxidaru_t$Pyxida Fish Tavern$pyxidaru_t$,
  $pyxidaru$Расположенный в центре Никосии, Pyxida — это первоклассный рыбный ресторан, известный своей свежей рыбой и элегантной атмосферой. От классического рыбного мезе до изысканной пасты с морепродуктами — он предлагает незабываемое кулинарное путешествие.$pyxidaru$,
  $pyxidazh_t$Pyxida Fish Tavern$pyxidazh_t$,
  $pyxidazh$Pyxida 位于尼科西亚市中心，是一家顶级的海鲜餐厅，以其新鲜的鱼类和优雅的氛围而闻名。从经典的海鲜小吃到美味的海鲜意大利面，它为首都的海鲜爱好者提供了一次难忘的烹饪之旅。$pyxidazh$,
  'fine_dining',
  false,
  35.1698,
  33.3602,
  'nicosia'
),
(
  'epsilon',
  'restaurants',
  'images/epsilon.jpg',
  '+357 25 020200',
  'https://www.limassolmarina.com/dining/epsilon',
  'https://maps.google.com/?q=34.6729,33.0436',
  $epsilonen_t$Epsilon Resto Bar$epsilonen_t$,
  $epsilonen$Situated in the luxurious Limassol Marina, Epsilon Resto Bar offers a chic dining experience with mesmerizing views of the Mediterranean. Its modern menu features creative international dishes, premium sushi, and signature cocktails, making it a hotspot for trendy and sophisticated dining.$epsilonen$,
  $epsilonel_t$Epsilon Resto Bar$epsilonel_t$,
  $epsilonel$Στην πολυτελή Μαρίνα Λεμεσού, το Epsilon Resto Bar προσφέρει μια κομψή γαστρονομική εμπειρία με μαγευτική θέα στη Μεσόγειο. Το μοντέρνο μενού του περιλαμβάνει δημιουργικά διεθνή πιάτα, premium σούσι και signature κοκτέιλ, καθιστώντας το ένα hotspot για μοντέρνα διασκέδαση.$epsilonel$,
  $epsilonru_t$Epsilon Resto Bar$epsilonru_t$,
  $epsilonru$Ресторан и бар Epsilon, расположенный в роскошной гавани Лимассола, предлагает шикарный ужин с завораживающим видом на Средиземное море. Его современное меню включает креативные блюда международной кухни, суши премиум-класса и фирменные коктейли.$epsilonru$,
  $epsilonzh_t$Epsilon Resto Bar$epsilonzh_t$,
  $epsilonzh$Epsilon Resto Bar 位于豪华的利马索尔码头，提供别致的用餐体验，可欣赏地中海的迷人景色。其现代菜单以创意的国际菜肴、优质寿司和招牌鸡尾酒为特色，使其成为时尚精致餐饮的热门地点。$epsilonzh$,
  'asian',
  false,
  34.6729,
  33.0436,
  'limassol'
),
(
  'militzis',
  'restaurants',
  'images/militzis.jpg',
  '+357 24 655867',
  'https://militzis.com/',
  'https://maps.google.com/?q=34.9118,33.6379',
  $militzisen_t$Militzis Traditional Tavern$militzisen_t$,
  $militzisen$A true Larnaca landmark overlooking the sea, Militzis has been serving authentic Cypriot cuisine for decades. Famous for its traditional wood-fired oven dishes, tender kleftiko, and local wines, this rustic tavern guarantees a genuine and hearty taste of Cyprus.$militzisen$,
  $militzisel_t$Ταβέρνα Μιλίτζης$militzisel_t$,
  $militzisel$Ένα πραγματικό ορόσημο της Λάρνακας με θέα στη θάλασσα, ο Μιλίτζης σερβίρει αυθεντική κυπριακή κουζίνα εδώ και δεκαετίες. Φημισμένη για τα παραδοσιακά πιάτα στον ξυλόφουρνο, το τρυφερό κλέφτικο και τα τοπικά κρασιά, αυτή η ρουστίκ ταβέρνα εγγυάται μια γνήσια γεύση της Κύπρου.$militzisel$,
  $militzisru_t$Таверна Militzis$militzisru_t$,
  $militzisru$Настоящая достопримечательность Ларнаки с видом на море, таверна Militzis десятилетиями подает аутентичные блюда кипрской кухни. Эта деревенская таверна, известная своими традиционными блюдами из дровяной печи, нежным клефтико и местными винами, гарантирует настоящий вкус Кипра.$militzisru$,
  $militziszh_t$Militzis Traditional Tavern$militziszh_t$,
  $militziszh$Militzis 是拉纳卡真正的地标建筑，俯瞰大海，几十年来一直供应正宗的塞浦路斯美食。这家质朴的酒馆以其传统的燃木烤炉菜肴、嫩滑的 Kleftiko 和当地葡萄酒而闻名，保证让您品尝到纯正而丰盛的塞浦路斯风味。$militziszh$,
  'traditional',
  false,
  34.9118,
  33.6379,
  'larnaca'
),
(
  'kalamiesrestaurant',
  'restaurants',
  'images/kalamiesrestaurant.jpg',
  '+357 23 831370',
  'https://www.kalamiesrestaurant.com/',
  'https://maps.google.com/?q=35.0124,34.0582',
  $kalamiesrestauranten_t$Kalamies Restaurant$kalamiesrestauranten_t$,
  $kalamiesrestauranten$Set on a picturesque sandy bay in Protaras, right next to a charming white-domed chapel, Kalamies is an iconic seaside restaurant. It has been delighting guests since 1976 with its exceptional fresh seafood, Mediterranean flavors, and romantic ambiance by the water's edge.$kalamiesrestauranten$,
  $kalamiesrestaurantel_t$Εστιατόριο Καλαμιές$kalamiesrestaurantel_t$,
  $kalamiesrestaurantel$Πάνω σε έναν γραφικό αμμώδη κόλπο στον Πρωταρά, ακριβώς δίπλα σε ένα λευκό εκκλησάκι, το Καλαμιές είναι ένα εμβληματικό παραθαλάσσιο εστιατόριο. Ενθουσιάζει τους επισκέπτες από το 1976 με τα εξαιρετικά φρέσκα θαλασσινά, τις μεσογειακές γεύσεις και τη ρομαντική ατμόσφαιρα δίπλα στο κύμα.$kalamiesrestaurantel$,
  $kalamiesrestaurantru_t$Ресторан Kalamies$kalamiesrestaurantru_t$,
  $kalamiesrestaurantru$Знаменитый прибрежный ресторан Kalamies расположен в живописной песчаной бухте в Протарасе, рядом с очаровательной часовней с белым куполом. С 1976 года он радует гостей свежайшими морепродуктами, средиземноморскими вкусами и романтической атмосферой у самой кромки воды.$kalamiesrestaurantru$,
  $kalamiesrestaurantzh_t$Kalamies Restaurant$kalamiesrestaurantzh_t$,
  $kalamiesrestaurantzh$Kalamies 是一家标志性的海滨餐厅，位于普罗塔拉斯风景如画的沙滩海湾，紧邻一座迷人的白顶小教堂。自 1976 年以来，这里一直以其卓越的新鲜海鲜、地中海风味和水边的浪漫氛围而令客人流连忘返。$kalamiesrestaurantzh$,
  'traditional',
  false,
  35.0124,
  34.0582,
  'famagusta'
),
(
  'bluelagoon',
  'beaches',
  'images/bluelagoon.jpg',
  null,
  null,
  'https://maps.google.com/?q=35.0772,32.3164',
  $bluelagoonen_t$Blue Lagoon$bluelagoonen_t$,
  $bluelagoonen$Located on the stunning Akamas Peninsula, the Blue Lagoon is the crown jewel of Paphos and one of the most breathtaking natural spots in Cyprus. Famous for its crystal-clear, shallow turquoise waters, it offers a magical setting for swimming and snorkeling. Accessible primarily by boat trips departing from the picturesque Latchi harbor or via rugged off-road routes, this pristine bay promises an unforgettable Mediterranean escape.$bluelagoonen$,
  $bluelagoonel_t$Γαλάζια Λίμνη (Blue Lagoon)$bluelagoonel_t$,
  $bluelagoonel$Βρίσκεται στη μαγευτική χερσόνησο του Ακάμα, η Γαλάζια Λίμνη (Blue Lagoon) είναι το απόλυτο στολίδι της Πάφου και ένα από τα πιο εντυπωσιακά φυσικά σημεία στην Κύπρο. Φημισμένη για τα κρυστάλλινα, ρηχά τιρκουάζ νερά της, προσφέρει ένα μαγευτικό σκηνικό για κολύμπι και εξερεύνηση με μάσκα. Με προσβασιμότητα κυρίως μέσω εκδρομών με σκάφος από το γραφικό λιμανάκι στο Λατσί ή μέσω χωματόδρομων, αυτός ο παρθένος κόλπος υπόσχεται μια αξέχαστη μεσογειακή απόδραση.$bluelagoonel$,
  $bluelagoonru_t$Голубая лагуна (Blue Lagoon)$bluelagoonru_t$,
  $bluelagoonru$Расположенная на потрясающем полуострове Акамас, Голубая лагуна является жемчужиной Пафоса и одним из самых захватывающих природных мест на Кипре. Известная своими кристально чистыми мелководными бирюзовыми водами, она предлагает волшебную обстановку для плавания и сноркелинга. Добраться сюда можно преимущественно на лодках из живописной гавани Лачи или по грунтовым дорогам, и этот первозданный залив обещает незабываемый средиземноморский отдых.$bluelagoonru$,
  $bluelagoonzh_t$蓝礁湖 (Blue Lagoon)$bluelagoonzh_t$,
  $bluelagoonzh$蓝礁湖 (Blue Lagoon) 位于迷人的阿卡马斯半岛 (Akamas Peninsula)，是帕福斯皇冠上的明珠，也是塞浦路斯最令人叹为观止的自然景点之一。这里以清澈见底的浅海绿松石色海水而闻名，为游泳和浮潜提供了神奇的环境。主要通过从风景如画的拉奇 (Latchi) 港口出发的游船或越野路线到达，这片原始的海湾保证为您带来难忘的地中海度假体验。$bluelagoonzh$,
  null,
  false,
  35.0772,
  32.3164,
  'paphos'
),
(
  'avakas',
  'things',
  'images/avakas.jpg',
  null,
  null,
  'https://maps.google.com/?q=34.9204,32.3431',
  $avakasen_t$Avakas Gorge Exploration$avakasen_t$,
  $avakasen$Hike through the breathtaking Avakas Gorge, a natural marvel carved by a river over limestone rock. Surrounded by towering vertical cliffs and lush vegetation, it offers an adventurous trail for nature lovers and hikers exploring the wild west coast of Cyprus.$avakasen$,
  $avakasel_t$Εξερεύνηση Φαραγγιού Αβάκα$avakasel_t$,
  $avakasel$Κάντε πεζοπορία μέσα στο εντυπωσιακό Φαράγγι του Αβάκα, ένα φυσικό αριστούργημα που έχει σμιλευτεί από ποταμό μέσα σε ασβεστολιθικά πετρώματα. Περιτριγυρισμένο από ψηλούς κάθετους βράχους και πλούσια βλάστηση, προσφέρει ένα περιπετειώδες μονοπάτι για τους λάτρεις της φύσης και της πεζοπορίας που εξερευνούν τη δυτική ακτή της Κύπρου.$avakasel$,
  $avakasru_t$Ущелье Авакас$avakasru_t$,
  $avakasru$Совершите пеший поход по захватывающему дух ущелью Авакас, природному чуду, высеченному рекой в известковых скалах. Окруженное высокими отвесными скалами и пышной растительностью, оно предлагает приключенческую тропу для любителей природы и пеших прогулок.$avakasru$,
  $avakaszh_t$阿瓦卡斯峡谷探索$avakaszh_t$,
  $avakaszh$徒步穿越令人叹为观止的阿瓦卡斯峡谷（Avakas Gorge），这是一处由河流在石灰岩上冲刷而成的自然奇观。四周环绕着高耸的垂直悬崖和郁郁葱葱的植被，为探索塞浦路斯西海岸的自然爱好者和徒步旅行者提供了一条充满冒险的步道。$avakaszh$,
  'promenades',
  false,
  34.9204,
  32.3431,
  'paphos'
),
(
  'tombsofthekings',
  'things',
  'images/tombsofthekings.jpg',
  null,
  null,
  'https://maps.google.com/?q=34.7753,32.4073',
  $tombsofthekingsen_t$Tombs of the Kings Archaeological Tour$tombsofthekingsen_t$,
  $tombsofthekingsen$Step back in time at the Tombs of the Kings, an impressive UNESCO World Heritage site dating back to the 4th century BC. Carved entirely out of solid rock and decorated with Doric pillars, this vast underground necropolis was built for high-ranking officials and aristocracy.$tombsofthekingsen$,
  $tombsofthekingsel_t$Αρχαιολογική Ξενάγηση στους Τάφους των Βασιλέων$tombsofthekingsel_t$,
  $tombsofthekingsel$Ταξιδέψτε πίσω στον χρόνο στους Τάφους των Βασιλέων, έναν εντυπωσιακό αρχαιολογικό χώρο παγκόσμιας κληρονομιάς της UNESCO που χρονολογείται από τον 4ο αιώνα π.Χ. Σκαλισμένη εξ ολοκλήρου από συμπαγή βράχο και διακοσμημένη με δωρικούς κίονες, αυτή η τεράστια υπόγεια νεκρόπολη χτίστηκε για υψηλόβαθμους αξιωματούχους και αριστοκράτες.$tombsofthekingsel$,
  $tombsofthekingsru_t$Царские гробницы$tombsofthekingsru_t$,
  $tombsofthekingsru$Перенеситесь в прошлое в Царских гробницах — впечатляющем объекте Всемирного наследия ЮНЕСКО, восходящем к IV веку до нашей эры. Высеченный целиком из цельной скалы и украшенный дорическими колоннами, этот огромный подземный некрополь был построен для высокопоставленных чиновников.$tombsofthekingsru$,
  $tombsofthekingszh_t$国王陵墓考古之旅$tombsofthekingszh_t$,
  $tombsofthekingszh$在国王陵墓（Tombs of the Kings）追溯历史，这是一处可追溯至公元前 4 世纪的宏伟联合国教科文组织世界遗产。这座巨大的地下大墓地完全由坚固的岩石雕刻而成，并饰有多立克式石柱，是为高官显贵和贵族建造的。$tombsofthekingszh$,
  'culture',
  false,
  34.7753,
  32.4073,
  'paphos'
),
(
  'larabay',
  'things',
  'images/larabay.jpg',
  null,
  null,
  'https://maps.google.com/?q=34.9533,32.3092',
  $larabayen_t$Lara Bay Turtle Conservation Visit$larabayen_t$,
  $larabayen$Visit the remote and unspoiled Lara Bay on the Akamas Peninsula, a dedicated sanctuary for endangered green and loggerhead sea turtles. Walk along the protected nesting grounds and learn about local conservation efforts while enjoying one of the island's most peaceful and untouched shores.$larabayen$,
  $larabayel_t$Επίσκεψη στον Σταθμό Προστασίας Χελωνών Λάρας$larabayel_t$,
  $larabayel$Επισκεφθείτε την απομακρυσμένη και παρθένα παραλία της Λάρας στη χερσόνησο του Ακάμα, ένα αφοσιωμένο καταφύγιο για τις απειλούμενες πράσινες χελώνες και καρέτα-καρέτα. Περπατήστε κατά μήκος των προστατευμένων περιοχών ωοτοκίας και ενημερωθείτε για τις τοπικές προσπάθειες διατήρησης απολαμβάνοντας μια από τις πιο ήσυχες ακτές.$larabayel$,
  $larabayru_t$Заповедник черепах Лара$larabayru_t$,
  $larabayru$Посетите удаленный и нетронутый пляж Лара на полуострове Акамас, являющийся заповедником для находящихся под угрозой исчезновения морских черепах. Прогуляйтесь по охраняемым местам гнездования и узнайте о местных природоохранных мероприятиях, наслаждаясь одним из самых тихих и нетронутых побережий.$larabayru$,
  $larabayzh_t$拉拉湾海龟保护探访$larabayzh_t$,
  $larabayzh$参观阿卡马斯半岛偏远且未受破坏的拉拉海滩（Lara Bay），这里是濒危绿海龟和蠵龟的专属保护区。沿着受保护的筑巢地漫步，了解当地的保护工作，同时享受岛上最宁静、原始的海岸线。$larabayzh$,
  'sea',
  false,
  34.9533,
  32.3092,
  'paphos'
),
(
  'adonisbaths',
  'things',
  'images/adonisbaths.jpg',
  null,
  null,
  'https://maps.google.com/?q=34.8824,32.4711',
  $adonisbathsen_t$Adonis Baths Waterfalls Experience$adonisbathsen_t$,
  $adonisbathsen$Discover the mythical Adonis Baths Waterfalls, located in a lush green valley hidden away in the hills of Paphos. Take a refreshing swim in the natural pool surrounded by impressive rock formations, statues of ancient Greek gods, and tranquil waterfalls.$adonisbathsen$,
  $adonisbathsel_t$Εμπειρία στους Καταρράκτες Λουτρών του Άδωνη$adonisbathsel_t$,
  $adonisbathsel$Ανακαλύψτε τους μυθικούς Καταρράκτες των Λουτρών του Άδωνη, που βρίσκονται σε μια καταπράσινη κοιλάδα κρυμμένη στους λόφους της Πάφου. Κάντε μια δροσερή βουτιά στη φυσική πισίνα που περιβάλλεται από εντυπωσιακούς βραχώδεις σχηματισμούς, αγάλματα αρχαίων Ελλήνων θεών και γαλήνιους καταρράκτες.$adonisbathsel$,
  $adonisbathsru_t$Водопады бань Адониса$adonisbathsru_t$,
  $adonisbathsru$Откройте для себя мифические водопады бань Адониса, расположенные в пышной зеленой долине, спрятанной в холмах Пафоса. Освежитесь в природном бассейне, окруженном впечатляющими скальными образованиями, статуями древнегреческих богов и водопадами.$adonisbathsru$,
  $adonisbathszh_t$阿多尼斯浴场瀑布体验$adonisbathszh_t$,
  $adonisbathszh$探索神话中的阿多尼斯浴场瀑布（Adonis Baths Waterfalls），它坐落在帕福斯群山中隐蔽的郁郁葱葱的绿色山谷里。在周围环绕着令人印象深刻的岩石地貌、古希腊神灵雕像和宁静瀑布的天然水池中清凉畅游。$adonisbathszh$,
  'promenades',
  false,
  34.8824,
  32.4711,
  'paphos'
),
(
  'sunshine',
  'things',
  'images/troodosjeep.jpg',
  null,
  null,
  'https://maps.google.com/?q=34.9241,32.8797',
  $troodosjeepen_t$Troodos Mountain Jeep Safari Adventure$troodosjeepen_t$,
  $troodosjeepen$Leave the city behind and head into the rugged terrain of the Troodos Mountains with an off-road jeep safari. Drive through dense pine forests, cross mountain streams, and discover hidden waterfalls and traditional mountain communities.$troodosjeepen$,
  $troodosjeepel_t$Περιπέτεια Jeep Safari στα Όρη Τροόδους$troodosjeepel_t$,
  $troodosjeepel$Αφήστε πίσω την πόλη και κατευθυνθείτε προς το τραχύ έδαφος των Ορέων Τροόδους με ένα off-road jeep safari. Οδηγήστε μέσα από πυκνά πευκοδάση, διασχίστε ορεινούς χειμάρρους και ανακαλύψτε κρυφούς καταρράκτες και παραδοσιακές ορεινές κοινότητες.$troodosjeepel$,
  $troodosjeepru_t$Джип-сафари в горах Троодос$troodosjeepru_t$,
  $troodosjeepru$Покиньте город и отправляйтесь в суровую местность гор Троодос на джип-сафари по бездорожью. Проедьте через густые сосновые леса, пересеките горные ручьи и откройте для себя скрытые водопады и традиционные горные общины.$troodosjeepru$,
  $troodosjeepzh_t$特罗多斯山脉吉普探险$troodosjeepzh_t$,
  $troodosjeepzh$离开城市，乘坐越野吉普车探险，深入特罗多斯山脉（Troodos Mountains）崎岖的地形。穿梭于茂密的松林，跨越山间溪流，探索隐藏的瀑布和传统的山地社区。$troodosjeepzh$,
  'safari',
  false,
  34.9241,
  32.8797,
  'limassol'
),
(
  'wine',
  'things',
  'images/omodos.jpg',
  null,
  null,
  'https://maps.google.com/?q=34.8483,32.8081',
  $omodosen_t$Omodos Village Cultural Walk$omodosen_t$,
  $omodosen$Explore the picturesque wine-producing village of Omodos, nestled in the foothills of Troodos. Wander through charming cobblestone streets, visit the historic Timios Stavros Monastery, and sample authentic local wines in traditional family-run cellars.$omodosen$,
  $omodosel_t$Πολιτιστικός Περίπατος στο Χωριό Όμοδος$omodosel_t$,
  $omodosel$Εξερευνήστε το γραφικό οινοπαραγωγικό χωριό Όμοδος, χτισμένο στους πρόποδες του Τροόδους. Περιπλανηθείτε σε γοητευτικά πλακόστρωτα σοκάκια, επισκεφθείτε το ιστορικό Μοναστήρι του Τιμίου Σταυρού και δοκιμάστε αυθεντικά τοπικά κρασιά σε παραδοσιακές οικογενειακές κάβες.$omodosel$,
  $omodosru_t$Прогулка по деревне Омодос$omodosru_t$,
  $omodosru$Исследуйте живописную винодельческую деревню Омодос, расположенную у подножия Троодоса. Прогуляйтесь по очаровательным мощеным улочкам, посетите исторический монастырь Тимиос Ставрос и отведайте аутентичные местные вина в традиционных погребах.$omodosru$,
  $omodoszh_t$奥莫多斯村庄文化漫步$omodoszh_t$,
  $omodoszh$探索坐落在特罗多斯山麓风景如画的产酒村奥莫多斯（Omodos）。漫步于迷人的鹅卵石街道，参观历史悠久的提米奥斯·斯塔夫罗斯修道院（Timios Stavros Monastery），并在传统的家庭酒窖中品尝地道的当地葡萄酒。$omodoszh$,
  'wine',
  false,
  34.8483,
  32.8081,
  'limassol'
),
(
  'kolossi',
  'things',
  'images/kolossi.jpg',
  null,
  null,
  'https://maps.google.com/?q=34.6653,32.9341',
  $kolossien_t$Kolossi Medieval Castle Visit$kolossien_t$,
  $kolossien$Discover the fascinating history of the Knights Templar at Kolossi Castle, a remarkable military architecture monument just outside Limassol. Climb to the roof for panoramic views of the surrounding vineyards and learn about the origins of the famous Commandaria wine.$kolossien$,
  $kolossiel_t$Επίσκεψη στο Μεσαιωνικό Κάστρο Κολλοσίου$kolossiel_t$,
  $kolossiel$Ανακαλύψτε τη συναρπαστική ιστορία των Ναϊτών Ιπποτών στο Κάστρο Κολλοσίου, ένα αξιοσημείωτο μνημείο στρατιωτικής αρχιτεκτονικής λίγο έξω από τη Λεμεσό. Ανεβείτε στην ταράτσα για πανοραμική θέα στους γύρω αμπελώνες και μάθετε για τις ρίζες του διάσημου κρασιού Κουμανταρία.$kolossiel$,
  $kolossiru_t$Средневековый замок Колосси$kolossiru_t$,
  $kolossiru$Откройте для себя захватывающую историю тамплиеров в замке Колосси, замечательном памятнике военной архитектуры недалеко от Лимассола. Поднимитесь на крышу, чтобы насладиться панорамным видом на виноградники и узнать об истоках знаменитого вина Коммандария.$kolossiru$,
  $kolossizh_t$科洛西中世纪城堡参观$kolossizh_t$,
  $kolossizh$在位于利马索尔郊外的非凡军事建筑古迹——科洛西城堡（Kolossi Castle）探索圣殿骑士团迷人的历史。登上屋顶欣赏周围葡萄园的全景，并了解著名康曼达里亚酒的起源。$kolossizh$,
  'culture',
  false,
  34.6653,
  32.9341,
  'limassol'
),
(
  'caledonia',
  'things',
  'images/caledonia.jpg',
  null,
  null,
  'https://maps.google.com/?q=34.8934,32.8632',
  $caledoniaen_t$Caledonia Waterfalls Nature Trail$caledoniaen_t$,
  $caledoniaen$Hike along the tranquil Caledonia Nature Trail near Platres village, leading through a dense forest full of rich flora. Follow the trickling stream up to the stunning Caledonia Waterfall, one of the most picturesque and refreshing natural escapes in the Troodos region.$caledoniaen$,
  $caledoniael_t$Μονοπάτι Φύσης Καταρράκτη Καληδονιών$caledoniael_t$,
  $caledoniael$Κάντε πεζοπορία κατά μήκος του γαλήνιου μονοπατιού της φύσης Καληδονιών κοντά στο χωριό Πλάτρες, το οποίο διασχίζει ένα πυκνό δάσος γεμάτο πλούσια χλωρίδα. Ακολουθήστε το ρυάκι μέχρι τον εκπληκτικό καταρράκτη των Καληδονιών, μια από τις πιο γραφικές φυσικές αποδράσεις στο Τροόδους.$caledoniael$,
  $caledoniaru_t$Тропа водопада Каледония$caledoniaru_t$,
  $caledoniaru$Совершите поход по тихой природной тропе Каледония возле деревни Платрес, пролегающей через густой лес. Следуйте вдоль ручья до потрясающего водопада Каледония, одного из самых живописных и освежающих уголков природы в регионе Троодос.$caledoniaru$,
  $caledoniazh_t$卡莱多尼亚瀑布自然步道$caledoniazh_t$,
  $caledoniazh$沿着普拉特雷斯村（Platres）附近宁静的卡莱多尼亚自然步道徒步旅行，穿过郁郁葱葱的繁茂森林。沿着涓涓细流一直走到令人叹为观止的卡莱多尼亚瀑布，这是特罗多斯地区最风景优美、最令人神清气爽的自然胜地之一。$caledoniazh$,
  'promenades',
  false,
  34.8934,
  32.8632,
  'limassol'
),
(
  'lefkara',
  'things',
  'images/lefkara.jpg',
  null,
  null,
  'https://maps.google.com/?q=34.8672,33.3074',
  $lefkaraen_t$Lefkara Village Handicraft & Silver Tour$lefkaraen_t$,
  $lefkaraen$Wander through the charming stone-built village of Lefkara, famous worldwide for its traditional lace embroidery (Lefkaritika) and intricate handmade silver crafts. Walk down the picturesque narrow alleys and meet local artisans preserving centuries-old cultural traditions.$lefkaraen$,
  $lefkarael_t$Περιήγηση Χειροτεχνίας & Ασημικών στα Λεύκαρα$lefkarael_t$,
  $lefkarael$Περιπλανηθείτε στο γοητευτικό πετρόχτιστο χωριό των Λευκάρων, παγκοσμίως διάσημο για τα παραδοσιακά κεντήματα (Λευκαρίτικα) και την περίτεχνη αργυροχοΐα. Περπατήστε στα γραφικά στενά σοκάκια και γνωρίστε ντόπιους τεχνίτες που διατηρούν αιώνιες πολιτιστικές παραδόσεις.$lefkarael$,
  $lefkararu_t$Ремесла и серебро Лефкары$lefkararu_t$,
  $lefkararu$Прогуляйтесь по очаровательной каменной деревне Лефкара, всемирно известной своим традиционным кружевом (лефкаритика) и сложным серебряным ремеслом. Пройдитесь по живописным узким улочкам и познакомьтесь с местными мастерами, сохраняющими вековые традиции.$lefkararu$,
  $lefkarazh_t$莱夫卡拉手工艺与银器之旅$lefkarazh_t$,
  $lefkarazh$漫步于迷人的石头村庄莱夫卡拉（Lefkara），这里以其传统的蕾丝刺绣（Lefkaritika）和精美的手工银器工艺闻名于世。走过风景如画的狭窄小巷，结识传承数百年文化传统的当地工匠。$lefkarazh$,
  'culture',
  false,
  34.8672,
  33.3074,
  'larnaca'
),
(
  'choirokoitia',
  'things',
  'images/choirokoitia.jpg',
  null,
  null,
  'https://maps.google.com/?q=34.7967,33.3436',
  $choirokoitiaen_t$Choirokoitia Neolithic Settlement Tour$choirokoitiaen_t$,
  $choirokoitiaen$Explore the Choirokoitia Neolithic Settlement, an exceptionally well-preserved prehistoric site and UNESCO World Heritage monument. Step inside the reconstructed circular stone houses to experience how early human communities lived in Cyprus over 9,000 years ago.$choirokoitiaen$,
  $choirokoitiael_t$Ξενάγηση στον Νεολιθικό Οικισμό Χοιροκοιτίας$choirokoitiael_t$,
  $choirokoitiael$Εξερευνήστε τον Νεολιθικό Οικισμό της Χοιροκοιτίας, έναν εξαιρετικά διατηρημένο προϊστορικό χώρο και μνημείο παγκόσμιας κληρονομιάς της UNESCO. Μπείτε μέσα στα ανασυσταθέντα κυκλικά πέτρινα σπίτια για να ζήσετε πώς ζούσαν οι πρώτες ανθρώπινες κοινότητες στην Κύπρο πριν από 9.000 χρόνια.$choirokoitiael$,
  $choirokoitiaru_t$Неолитическое поселение Хирокития$choirokoitiaru_t$,
  $choirokoitiaru$Исследуйте неолитическое поселение Хирокития, прекрасно сохранившийся доисторический памятник и объект Всемирного наследия ЮНЕСКО. Загляните внутрь реконструированных круглых каменных домов, чтобы узнать, как жили люди на Кипре 9 000 лет назад.$choirokoitiaru$,
  $choirokoitiazh_t$希罗科蒂亚新石器聚落参观$choirokoitiazh_t$,
  $choirokoitiazh$探索希罗科蒂亚（Choirokoitia）新石器时代定居点，这是一处保存极其完好的史前遗址和联合国教科文组织世界遗产。走进重建的圆形石屋，体验 9000 多年前早期人类社群在塞浦路斯的生活方式。$choirokoitiazh$,
  'culture',
  false,
  34.7967,
  33.3436,
  'larnaca'
),
(
  'camelpark',
  'things',
  'images/camelpark.jpg',
  null,
  null,
  'https://maps.google.com/?q=34.8024,33.4906',
  $camelparken_t$Camel Park Mazotos Family Day$camelparken_t$,
  $camelparken$Enjoy a fun-filled family day out at the Camel Park in Mazotos, located just a short drive from Larnaca. Ride gentle camels, feed various farm animals, enjoy the swimming pool, and explore the relaxing recreational areas designed for visitors of all ages.$camelparken$,
  $camelparkel_t$Οικογενειακή Μέρα στο Camel Park Μαζωτού$camelparkel_t$,
  $camelparkel$Απολαύστε μια διασκεδαστική οικογενειακή μέρα στο Camel Park στο Μαζωτό, σε κοντινή απόσταση οδικώς από τη Λάρνακα. Κάντε βόλτα με ήρεμες καμήλες, ταΐστε διάφορα ζώα φάρμας, απολαύστε την πισίνα και εξερευνήστε τους χώρους αναψυχής για επισκέπτες όλων των ηλικιών.$camelparkel$,
  $camelparkru_t$Парк верблюдов в Мазотосе$camelparkru_t$,
  $camelparkru$Проведите веселый семейный день в Парке верблюдов в Мазотосе, расположенном всего в нескольких минутах езды от Ларнаки. Покатитесь на спокойных верблюдах, покормите животных, искупайтесь в бассейне и отдохните в зонах отдыха.$camelparkru$,
  $camelparkzh_t$马佐托斯骆驼公园家庭日$camelparkzh_t$,
  $camelparkzh$在距离拉纳卡仅车程之遥的马佐托斯（Mazotos）骆驼公园享受充满乐趣的家庭日。骑着温顺的骆驼，喂养各种农场动物，享受游泳池，并探索专为所有年龄段游客设计的放松休闲区。$camelparkzh$,
  'promenades',
  false,
  34.8024,
  33.4906,
  'larnaca'
),
(
  'angeloktisti',
  'things',
  'images/angeloktisti.jpg',
  null,
  null,
  'https://maps.google.com/?q=34.8473,33.5718',
  $angeloktistien_t$Angeloktisti Church Architectural Tour$angeloktistien_t$,
  $angeloktistien$Visit the remarkable 11th-century Church of Panagia Angeloktisti in Kiti village, famous worldwide for its rare 6th-century Byzantine mosaic of the Virgin Mary. Admire its unique early Christian architecture and priceless historical religious art.$angeloktistien$,
  $angeloktistiel_t$Αρχιτεκτονική Περιήγηση στην Εκκλησία Παναγίας Αγγελόκτιστης$angeloktistiel_t$,
  $angeloktistiel$Επισκεφθείτε την αξιοσημείωτη Εκκλησία της Παναγίας Αγγελόκτιστης του 11ου αιώνα στο χωριό Κίτι, παγκοσμίως διάσημη για το σπάνιο βυζαντινό ψηφιδωτό της Παναγίας του 6ου αιώνα. Θαυμάστε τη μοναδική πρωτοχριστιανική αρχιτεκτονική και την ανεκτίμητη θρησκευτική τέχνη.$angeloktistiel$,
  $angeloktistiru_t$Церковь Панагия Ангелоктисти$angeloktistiru_t$,
  $angeloktistiru$Посетите замечательную церковь Панагия Ангелоктисти XI века в деревне Кити, всемирно известную своей редкой византийской мозаикой Девы Марии VI века. Полюбуйтесь уникальной архитектурой и бесценным искусством.$angeloktistiru$,
  $angeloktistizh_t$安格洛克蒂斯蒂教堂建筑之旅$angeloktistizh_t$,
  $angeloktistizh$参观基蒂村（Kiti）建于 11 世纪卓越的帕纳吉亚·安格洛克蒂斯蒂教堂（Panagia Angeloktisti Church），该教堂以其罕见的 6 世纪圣母拜占庭马赛克而闻名于世。欣赏其独特的早期基督教建筑和无价的历史宗教艺术。$angeloktistizh$,
  'culture',
  false,
  34.8473,
  33.5718,
  'larnaca'
),
(
  'thalassa',
  'things',
  'images/thalassa.jpg',
  null,
  null,
  'https://maps.google.com/?q=34.9877,33.9991',
  $thalassaen_t$Thalassa Municipal Museum Maritime Tour$thalassaen_t$,
  $thalassaen$Immerse yourself in the maritime history of Cyprus at the Thalassa Museum in Ayia Napa. Explore fascinating exhibits, including a life-size replica of an ancient Greek merchant ship that sank off the coast, alongside rich marine fossils and historical artifacts.$thalassaen$,
  $thalassael_t$Ναυτική Περιήγηση στο Δημοτικό Μουσείο Θάλασσα$thalassael_t$,
  $thalassael$Βυθιστείτε στη ναυτική ιστορία της Κύπρου στο Μουσείο Θάλασσα στην Αγία Νάπα. Εξερευνήστε συναρπαστικά εκθέματα, συμπεριλαμβανομένου ενός αντιγράφου σε φυσικό μέγεθος ενός αρχαίου ελληνικού εμπορικού πλοίου που ναυάγησε στις ακτές, καθώς και πλούσια θαλάσσια απολιθώματα.$thalassael$,
  $thalassaru_t$Музей Таласса$thalassaru_t$,
  $thalassaru$Погрузитесь в морскую историю Кипра в музее Таласса в Айя-Напе. Исследуйте увлекательные экспонаты, включая полноразмерную копию древнегреческого торгового судна, затонувшего у берегов, а также морские окаменелости.$thalassaru$,
  $thalassazh_t$塔拉萨海事博物馆参观$thalassazh_t$,
  $thalassazh$在圣纳帕的塔拉萨博物馆（Thalassa Museum）沉浸在塞浦路斯的航海历史中。探索引人入胜的展品，包括在海岸附近沉没的古希腊商船的实物大小复制品，以及丰富的海洋化石。$thalassazh$,
  'culture',
  false,
  34.9877,
  33.9991,
  'famagusta'
),
(
  'sculpturepark',
  'things',
  'images/sculpturepark.jpg',
  null,
  null,
  'https://maps.google.com/?q=34.9872,34.0014',
  $sculptureparken_t$Ayia Napa Sculpture & Cactus Park Walk$sculptureparken_t$,
  $sculptureparken$Stroll through the unique open-air Ayia Napa Sculpture Park and the adjacent Cactus Park, situated on a coastal hill. Discover impressive contemporary artworks created by international sculptors contrasted against a massive collection of desert plants and sweeping sea views.$sculptureparken$,
  $sculptureparkel_t$Βόλτα στα Πάρκα Γλυπτικής και Κάκτων Αγίας Νάπας$sculptureparkel_t$,
  $sculptureparkel$Κάντε έναν περίπατο στο μοναδικό υπαίθριο Πάρκο Γλυπτικής της Αγίας Νάπας και στο διπλανό Πάρκο Κάκτων, χτισμένα σε παραθαλάσσιο λόφο. Ανακαλύψτε εντυπωσιακά σύγχρονα έργα τέχνης από διεθνείς γλύπτες σε αντίθεση με μια τεράστια συλλογή φυτών ερήμου και πανοραμική θέα στη θάλασσα.$sculptureparkel$,
  $sculptureparkru_t$Парк скульптур и кактусов$sculptureparkru_t$,
  $sculptureparkru$Прогуляйтесь по уникальному парку скульптур под открытым небом в Айя-Напе и соседнему парку кактусов, расположенным на прибрежном холме. Откройте для себя современные произведения искусства и огромную коллекцию пустынных растений.$sculptureparkru$,
  $sculptureparkzh_t$圣纳帕雕塑与仙人掌公园漫步$sculptureparkzh_t$,
  $sculptureparkzh$漫步于独具特色的露天圣纳帕雕塑公园和毗邻的仙人掌公园，它们坐落在一座海滨小山上。探索由国际雕塑家创作的令人印象深刻的当代艺术品，并与庞大的沙漠植物收藏和壮丽的海景交相辉映。$sculptureparkzh$,
  'promenades',
  false,
  34.9872,
  34.0014,
  'famagusta'
),
(
  'liopetri-river',
  'things',
  'images/liopetri.jpg',
  null,
  null,
  'https://maps.google.com/?q=35.0071,33.8927',
  $liopetrien_t$Liopetri River & Fishing Shelter Visit$liopetrien_t$,
  $liopetrien$Visit the peaceful and picturesque Liopetri River, a natural estuary often referred to as a hidden paradise. Admire the traditional wooden fishermen's shacks, watch local boats glide across calm waters, and enjoy a quiet escape away from busy tourist spots.$liopetrien$,
  $liopetriel_t$Επίσκεψη στον Ποταμό & Ψαρολίμανο Λιοπετρίου$liopetriel_t$,
  $liopetriel$Επισκεφθείτε τον γαλήνιο και γραφικό Ποταμό Λιοπετρίου, ένα φυσικό εκβολικό τοπίο που συχνά αποκαλείται κρυφός παράδεισος. Θαυμάστε τις παραδοσιακές ξύλινες καλύβες ψαράδων, παρακολουθήστε τις βάρκες να γλιστρούν στα ήρεμα νερά και απολαύστε μια ήσυχη απόδραση μακριά από τα πολυσύχναστα τουριστικά σημεία.$liopetriel$,
  $liopetriru_t$Река Лиопетри$liopetriru_t$,
  $liopetriru$Посетите мирную и живописную реку Лиопетри, естественный эстуарий, который часто называют скрытым раем. Полюбуйтесь традиционными деревянными рыбацкими хижинами, понаблюдайте за лодками на спокойной воде.$liopetriru$,
  $liopetrizh_t$利奥佩特里河与渔港探访$liopetrizh_t$,
  $liopetrizh$参观宁静优美的利奥佩特里河（Liopetri River），这是一个常被称为隐蔽天堂的天然入海口。欣赏传统的木制渔夫小屋，看着当地的小船在平静的水面上滑行，享受远离繁忙旅游景点的宁静度假。$liopetrizh$,
  'promenades',
  false,
  35.0071,
  33.8927,
  'famagusta'
),
(
  'deryneia',
  'things',
  'images/deryneia.jpg',
  null,
  null,
  'https://maps.google.com/?q=35.0758,33.9608',
  $deryneiaen_t$Deryneia Cultural & Viewpoint Stop$deryneiaen_t$,
  $deryneiaen$Discover the cultural heritage of the Famagusta region in Deryneia. Visit traditional local craft workshops and stop by the special observatory viewpoint to learn about the history of the area and view the fenced ghost town of Varosha from a distance.$deryneiaen$,
  $deryneiael_t$Σταθμός Πολιτισμού & Θέασης στη Δερύνεια$deryneiael_t$,
  $deryneiael$Ανακαλύψτε την πολιτιστική κληρονομιά της περιοχής Αμμοχώστου στη Δερύνεια. Επισκεφθείτε παραδοσιακά τοπικά εργαστήρια χειροτεχνίας και σταθείτε στο ειδικό σημείο παρατήρησης για να μάθετε την ιστορία της περιοχής και να δείτε από μακριά την περιφραγμένη πόλη-φάντασμα των Βαρωσίων.$deryneiael$,
  $deryneiaru_t$Смотровая площадка Деринеи$deryneiaru_t$,
  $deryneiaru$Откройте для себя культурное наследие региона Фамагуста в Деринее. Посетите традиционные мастерские и остановитесь у специальной смотровой площадки, чтобы узнать историю региона и увидеть огороженный город-призрак Вароша.$deryneiaru$,
  $deryneiazh_t$德里尼亚文化与观景停留$deryneiazh_t$,
  $deryneiazh$探索德里尼亚（Deryneia）法马古斯塔地区的文化遗产。参观传统的当地手工艺作坊，并在特殊的观景台驻足，了解该地区的历史，并从远处眺望被围起来的鬼城瓦罗莎（Varosha）。$deryneiazh$,
  'culture',
  false,
  35.0758,
  33.9608,
  'famagusta'
),
(
  'leventis',
  'things',
  'images/leventis.jpg',
  null,
  null,
  'https://maps.google.com/?q=35.1719,33.3634',
  $leventisen_t$Leventis Municipal Museum Cultural Walk$leventisen_t$,
  $leventisen$Explore the Leventis Municipal Museum of Nicosia, dedicated entirely to the rich history and social life of the capital from ancient times to the present day. Located in the old town, it offers fascinating insights into the city's unique multicultural heritage.$leventisen$,
  $leventisel_t$Πολιτιστικός Περίπατος στο Δημοτικό Μουσείο Λεβέντη$leventisel_t$,
  $leventisel$Εξερευνήστε το Λεβέντειο Δημοτικό Μουσείο Λευκωσίας, αφιερωμένο εξ ολοκλήρου στην πλούσια ιστορία και την κοινωνική ζωή της πρωτεύουσας από την αρχαιότητα έως σήμερα. Βρίσκεται στην παλιά πόλη και προσφέρει συναρπαστικές ματιές στη μοναδική πολυπολιτισμική κληρονομιά της πόλης.$leventisel$,
  $leventisru_t$Муниципальный музей Левентис$leventisru_t$,
  $leventisru$Исследуйте муниципальный музей Левентис в Никосии, посвященный богатой истории и социальной жизни столицы с древнейших времен до наших дней. Расположенный в старом городе, он предлагает увлекательное знакомство с наследием.$leventisru$,
  $leventiszh_t$莱文蒂斯市博物馆文化漫步$leventiszh_t$,
  $leventiszh$探索尼科西亚莱文蒂斯市博物馆（Leventis Municipal Museum），该博物馆完全致力于展示首都从古代到今天丰富的历史和社会生活。它位于老城区，让您深入了解这座城市独特的多元文化遗产。$leventiszh$,
  'culture',
  false,
  35.1719,
  33.3634,
  'nicosia'
),
(
  'buyukhan',
  'things',
  'images/buyukhan.jpg',
  null,
  null,
  'https://maps.google.com/?q=35.1765,33.3617',
  $buyukhanen_t$Buyuk Han Ottoman Architecture Tour$buyukhanen_t$,
  $buyukhanen$Step inside the magnificent Buyuk Han, the largest and most impressive Ottoman caravanserai in Cyprus, built in 1572. Wander through its historic arcaded courtyard, which now hosts thriving artisan shops, art galleries, and cozy traditional coffee houses.$buyukhanen$,
  $buyukhanel_t$Περιήγηση στην Οθωμανική Αρχιτεκτονική του Μπουγιούκ Χαν$buyukhanel_t$,
  $buyukhanel$Μπείτε μέσα στο μεγαλοπρεπές Μπουγιούκ Χαν, το μεγαλύτερο και πιο εντυπωσιακό οθωμανικό χάνι στην Κύπρο, που χτίστηκε το 1572. Περιπλανηθείτε στην ιστορική εσωτερική αυλή του, η οποία φιλοξενεί τώρα ακμάζοντα εργαστήρια τεχνιτών, γκαλερί τέχνης και ζεστά παραδοσιακά καφενεία.$buyukhanel$,
  $buyukhanru_t$Буюк-Хан$buyukhanru_t$,
  $buyukhanru$Зайдите в великолепный Буюк-Хан, самый большой и впечатляющий османский караван-сарай на Кипре, построенный в 1572 году. Прогуляйтесь по его историческому внутреннему двору, где теперь работают ремесленные мастерские и кафе.$buyukhanru$,
  $buyukhanzh_t$布于克汗奥斯曼建筑之旅$buyukhanzh_t$,
  $buyukhanzh$走进宏伟的布于克汗（Buyuk Han），这是塞浦路斯最大、最令人印象深刻的奥斯曼帝国商队旅馆，建于 1572 年。漫步于其历史悠久的拱形庭院中，这里现在拥有繁荣的手工艺品店、艺术画廊和温馨的传统咖啡馆。$buyukhanzh$,
  'culture',
  false,
  35.1765,
  33.3617,
  'nicosia'
),
(
  'museum-nic',
  'things',
  'images/cyprusmuseum.jpg',
  null,
  null,
  'https://maps.google.com/?q=35.1714,33.3554',
  $cyprusmuseumen_t$Cyprus Museum Archaeological Exploration$cyprusmuseumen_t$,
  $cyprusmuseumen$Discover an unmatched collection of antiquities at the Cyprus Museum in Nicosia, the oldest and largest archaeological museum on the island. Marvel at priceless artifacts spanning from the Neolithic period through the Bronze Age and the Roman era.$cyprusmuseumen$,
  $cyprusmuseumel_t$Αρχαιολογική Εξερεύνηση στο Κυπριακό Μουσείο$cyprusmuseumel_t$,
  $cyprusmuseumel$Ανακαλύψτε μια ασύγκριτη συλλογή αρχαιοτήτων στο Κυπριακό Μουσείο στη Λευκωσία, το παλαιότερο και μεγαλύτερο αρχαιολογικό μουσείο του νησιού. Θαυμάστε ανεκτίμητα αντικείμενα που εκτείνονται από τη νεολιθική εποχή, την εποχή του Χαλκού έως τη ρωμαϊκή περίοδο.$cyprusmuseumel$,
  $cyprusmuseumru_t$Кипрский музей$cyprusmuseumru_t$,
  $cyprusmuseumru$Откройте для себя непревзойденную коллекцию древностей в Кипрском музее в Никосии, старейшем и крупнейшем археологическом музее острова. Полюбуйтесь бесценными артефактами от неолита до римской эпохи.$cyprusmuseumru$,
  $cyprusmuseumzh_t$塞浦路斯博物馆考古探索$cyprusmuseumzh_t$,
  $cyprusmuseumzh$在尼科西亚的塞浦路斯博物馆（Cyprus Museum）探索无与伦比的古代文物收藏，这是岛上最古老、最大的考古博物馆。惊叹于从新石器时代、青铜时代到罗马时代的无价文物。$cyprusmuseumzh$,
  'culture',
  false,
  35.1714,
  33.3554,
  'nicosia'
),
(
  'nicosia-walk',
  'things',
  'images/dodekapente.jpg',
  null,
  null,
  'https://maps.google.com/?q=35.1743,33.3686',
  $dodekapenteen_t$Dodeka Pente Local Food & Art Quarter Walk$dodekapenteen_t$,
  $dodekapenteen$Stroll through the charming old neighborhoods of Nicosia near the Chrysaliniotissa area, known for its creative community, restored traditional houses, hidden local art studios, and authentic neighborhood tavernas offering a true taste of capital life.$dodekapenteen$,
  $dodekapenteel_t$Βόλτα στη Γειτονιά Τέχνης & Γεύσης$dodekapenteel_t$,
  $dodekapenteel$Κάντε έναν περίπατο στις γοητευτικές παλιές γειτονιές της Λευκωσίας κοντά στην περιοχή της Χρυσαλινιώτισσας, γνωστή για τη δημιουργική της κοινότητα, τα αναπαλαιωμένα παραδοσιακά σπίτια, τα κρυμμένα καλλιτεχνικά στούντιο και τις αυθεντικές ταβέρνες.$dodekapenteel$,
  $dodekapenteru_t$Квартал еды и искусства$dodekapenteru_t$,
  $dodekapenteru$Прогуляйтесь по очаровательным старым кварталам Никосии возле района Хрисалиниотисса, известного своим творческим сообществом, отреставрированными домами, художественными студиями и аутентичными тавернами.$dodekapenteru$,
  $dodekapentezh_t$美食与艺术街区漫步$dodekapentezh_t$,
  $dodekapentezh$漫步于尼科西亚 Chrysaliniotissa 地区附近迷人的老街区，这里以其充满创意的社区、修复的传统房屋、隐蔽的当地艺术工作室和提供地道首都生活风味的传统小酒馆而闻名。$dodekapentezh$,
  'promenades',
  false,
  35.1743,
  33.3686,
  'nicosia'
)
on conflict (id) do update set
  category = excluded.category,
  image_url = excluded.image_url,
  phone = excluded.phone,
  website = excluded.website,
  map_link = excluded.map_link,
  title_en = excluded.title_en,
  desc_en = excluded.desc_en,
  title_el = excluded.title_el,
  desc_el = excluded.desc_el,
  title_ru = excluded.title_ru,
  desc_ru = excluded.desc_ru,
  title_zh = excluded.title_zh,
  desc_zh = excluded.desc_zh,
  subcategory = excluded.subcategory,
  lat = excluded.lat,
  lng = excluded.lng,
  town = excluded.town;
