insert into public.places (
  id, category, image_url, phone, website, map_link,
  title_en, desc_en, title_el, desc_el, title_ru, desc_ru, title_zh, desc_zh,
  subcategory, is_best_of_month, lat, lng, town
) values
(
  'zephyros',
  'restaurants',
  'images/zephyros.jpg?v=rest3',
  '+357 24 657198',
  'https://www.facebook.com/ZephyrosBeachTavern',
  'https://maps.google.com/?q=34.899682,33.6382862',
  $zephyrosen_t$Zephyros Restaurant$zephyrosen_t$,
  $zephyrosen$Located near the Larnaca fishing harbor, Zephyros is a legendary seafood tavern operating for decades. Famous among locals for its fresh catch of the day, rich fish meze, and vibrant atmosphere, it offers an authentic Cypriot seafood experience right by the sea.$zephyrosen$,
  $zephyrosel_t$Ψαροταβέρνα Zephyros$zephyrosel_t$,
  $zephyrosel$Κοντά στο ψαρολίμανο της Λάρνακας, το Zephyros είναι μια θρυλική ψαροταβέρνα που λειτουργεί εδώ και δεκαετίες. Διάσημο στους ντόπιους για την ολόφρεσκη ψαριά της ημέρας, τον πλούσιο ψαρομεζέ και τη ζωντανή ατμόσφαιρα, προσφέρει μια αυθεντική κυπριακή εμπειρία θαλασσινών δίπλα στο κύμα.$zephyrosel$,
  $zephyrosru_t$Ресторан Zephyros$zephyrosru_t$,
  $zephyrosru$Расположенная недалеко от рыбацкой гавани Ларнаки, Zephyros — это легендарная рыбная таверна, работающая уже несколько десятилетий. Известная среди местных жителей своим свежим уловом дня, богатым рыбным мезе и оживленной атмосферой, она предлагает аутентичный кипрский опыт морепродуктов у моря.$zephyrosru$,
  $zephyroszh_t$Zephyros 海鲜餐厅$zephyroszh_t$,
  $zephyroszh$Zephyros 位于拉纳卡渔港附近，是一家经营了数十年的传奇海鲜餐厅。这里以每日新鲜捕捞的海鲜、丰盛的鱼类小吃 (Meze) 和热闹的氛围在当地人中享有盛誉，在海边为您提供地道的塞浦路斯海鲜体验。$zephyroszh$,
  'traditional',
  false,
  34.899682,
  33.6382862,
  'larnaca'
),
(
  'columbia',
  'restaurants',
  'images/columbia.jpg?v=rest3',
  '+357 25 278000',
  'https://columbiavenuecentre.com/',
  'https://maps.google.com/?q=34.6771193,33.0479537',
  $columbiaen_t$Columbia Steak House$columbiaen_t$,
  $columbiaen$Situated in the heart of Limassol, Columbia Steak House is the ultimate destination for meat lovers. Offering an elegant, cosmopolitan setting, it specializes in premium USDA and Black Angus steaks perfectly cooked to order, complemented by an impressive wine cellar and world-class service.$columbiaen$,
  $columbiael_t$Columbia Steak House$columbiael_t$,
  $columbiael$Στην καρδιά της Λεμεσού, το Columbia Steak House είναι ο απόλυτος προορισμός για τους λάτρεις του κρέατος. Προσφέροντας ένα κομψό, κοσμοπολίτικο περιβάλλον, ειδικεύεται σε premium κοπές USDA και Black Angus, άψογα ψημένες, οι οποίες συνοδεύονται από μια εντυπωσιακή κάβα κρασιών και υπηρεσίες παγκόσμιας κλάσης.$columbiael$,
  $columbiaru_t$Columbia Steak House$columbiaru_t$,
  $columbiaru$Columbia Steak House, расположенный в самом центре Лимассола, — это идеальное место для любителей мяса. Предлагая элегантную, космополитичную обстановку, ресторан специализируется на стейках премиум-класса USDA и Black Angus, идеально приготовленных на заказ, дополненных впечатляющим винным погребом и первоклассным обслуживанием.$columbiaru$,
  $columbiazh_t$Columbia Steak House$columbiazh_t$,
  $columbiazh$Columbia Steak House 位于利马索尔市中心，是肉类爱好者的终极圣地。餐厅环境优雅、充满国际大都市气息，专营优质的美国农业部 (USDA) 认证和黑安格斯牛排，烹饪完美，并配有令人印象深刻的酒窖和世界一流的服务。$columbiazh$,
  'fine_dining',
  false,
  34.6771193,
  33.0479537,
  'limassol'
),
(
  'beba',
  'restaurants',
  'images/beba.jpg?v=rest3',
  '+357 22 252626',
  null,
  'https://maps.google.com/?q=35.1688429,33.3697502',
  $bebaen_t$Beba Restaurant$bebaen_t$,
  $bebaen$A culinary hotspot in Nicosia, Beba seamlessly blends traditional Cypriot and Greek recipes with modern Mediterranean flair. With a beautiful internal courtyard and a strong focus on seasonal ingredients, their signature dishes cooked in a wood-fired oven make it an absolute must-visit for food enthusiasts.$bebaen$,
  $bebael_t$Εστιατόριο Μπέμπα (Beba)$bebael_t$,
  $bebael$Ένα γαστρονομικό hotspot στη Λευκωσία, το εστιατόριο Μπέμπα (Beba) συνδυάζει άψογα τις παραδοσιακές κυπριακές και ελληνικές συνταγές με μια σύγχρονη μεσογειακή πινελιά. Με μια πανέμορφη εσωτερική αυλή και έμφαση στα εποχιακά υλικά, τα πιάτα κατατεθέντα που ψήνονται στον ξυλόφουρνο το καθιστούν απαραίτητο προορισμό για τους καλοφαγάδες.$bebael$,
  $bebaru_t$Ресторан Beba$bebaru_t$,
  $bebaru$Кулинарная точка в Никосии, Beba органично сочетает традиционные кипрские и греческие рецепты с современным средиземноморским колоритом. Красивый внутренний двор, акцент на сезонных ингредиентах и фирменные блюда, приготовленные в дровяной печи, делают этот ресторан обязательным для посещения гурманами.$bebaru$,
  $bebazh_t$Beba 餐厅$bebazh_t$,
  $bebazh$Beba 是尼科西亚的烹饪热点，将传统的塞浦路斯和希腊食谱与现代地中海风味完美融合。这里拥有美丽的内部庭院，注重时令食材，其在燃木烤炉中烹制的招牌菜肴使其成为美食爱好者的必游之地。$bebazh$,
  'traditional',
  false,
  35.1688429,
  33.3697502,
  'nicosia'
),
(
  'losbandidos',
  'restaurants',
  'images/losbandidos.jpg',
  '+357 23 723258',
  'https://www.losbandidosmexican.com',
  'https://maps.google.com/?q=34.9905591,33.9986323',
  $losbandidosen_t$Los Bandidos$losbandidosen_t$,
  $losbandidosen$Located right in the bustling center of Ayia Napa, Los Bandidos is arguably the most famous and lively Mexican restaurant on the island. Offering legendary margaritas, authentic fajitas, and a vibrant, colorful décor, it guarantees a fun, high-energy dining experience for groups and families.$losbandidosen$,
  $losbandidosel_t$Los Bandidos$losbandidosel_t$,
  $losbandidosel$Στο πολυσύχναστο κέντρο της Αγίας Νάπας, το Los Bandidos είναι ίσως το πιο διάσημο και ζωντανό μεξικάνικο εστιατόριο του νησιού. Προσφέροντας θρυλικές μαργαρίτες, αυθεντικά φαχίτας και μια εντυπωσιακή πολύχρωμη διακόσμηση, εγγυάται μια διασκεδαστική, γεμάτη ενέργεια γαστρονομική εμπειρία για παρέες και οικογένειες.$losbandidosel$,
  $losbandidosru_t$Los Bandidos$losbandidosru_t$,
  $losbandidosru$Los Bandidos, расположенный в самом оживленном центре Айя-Напы, является, пожалуй, самым известным и веселым мексиканским рестораном на острове. Предлагая легендарные маргариты, аутентичные фахитас и яркий декор, он гарантирует веселое и энергичное застолье для компаний и семей.$losbandidosru$,
  $losbandidoszh_t$Los Bandidos$losbandidoszh_t$,
  $losbandidoszh$Los Bandidos 位于圣纳帕熙熙攘攘的中心，可以说是岛上最著名、最热闹的墨西哥餐厅。这里提供传奇的玛格丽塔酒、正宗的法吉塔 (Fajitas) 和充满活力的纯正装饰，保证为团队和家庭带来充满乐趣和高能量的用餐体验。$losbandidoszh$,
  'mexican',
  false,
  34.9905591,
  33.9986323,
  'famagusta'
),
(
  'ouzeri',
  'restaurants',
  'images/ouzeri.jpg?v=rest3',
  '+357 26 888700',
  'https://www.almyra.com/dine/ouzeri-restaurant',
  'https://maps.google.com/?q=34.7541191,32.4189117',
  $ouzerien_t$Ouzeri at Almyra$ouzerien_t$,
  $ouzerien$Situated right on the Paphos seafront promenade within the luxurious Almyra Hotel, Ouzeri is the perfect spot for a romantic dinner. Enjoy traditional Cypriot meze and local wines with the soothing sound of the waves and unobstructed views of the Mediterranean sunset.$ouzerien$,
  $ouzeriel_t$Ouzeri at Almyra$ouzeriel_t$,
  $ouzeriel$Πάνω στον παραλιακό πεζόδρομο της Πάφου, στο πολυτελές ξενοδοχείο Almyra, το Ouzeri είναι το ιδανικό μέρος για ένα ρομαντικό δείπνο. Απολαύστε παραδοσιακούς κυπριακούς μεζέδες και τοπικά κρασιά με τον χαλαρωτικό ήχο των κυμάτων και ανεμπόδιστη θέα στο μεσογειακό ηλιοβασίλεμα.$ouzeriel$,
  $ouzeriru_t$Ouzeri at Almyra$ouzeriru_t$,
  $ouzeriru$Расположенный прямо на набережной Пафоса на территории роскошного отеля Almyra, ресторан Ouzeri — идеальное место для романтического ужина. Насладитесь традиционным кипрским мезе и местными винами под успокаивающий шум волн и беспрепятственный вид на средиземноморский закат.$ouzeriru$,
  $ouzerizh_t$Almyra 酒店 Ouzeri$ouzerizh_t$,
  $ouzerizh$Ouzeri 位于豪华的 Almyra 酒店内的帕福斯海滨长廊上，是享用浪漫晚餐的理想场所。伴随着舒缓的海浪声和地中海日落的一览无余的美景，您可以尽情享用传统的塞浦路斯小吃和当地葡萄酒。$ouzerizh$,
  'traditional',
  false,
  34.7541191,
  32.4189117,
  'paphos'
)
on conflict (id) do update set
  category = excluded.category,
  image_url = excluded.image_url,
  phone = excluded.phone,
  website = excluded.website,
  map_link = excluded.map_link,
  title_en = excluded.title_en,
  desc_en = excluded.desc_en,
  title_el = excluded.title_el,
  desc_el = excluded.desc_el,
  title_ru = excluded.title_ru,
  desc_ru = excluded.desc_ru,
  title_zh = excluded.title_zh,
  desc_zh = excluded.desc_zh,
  subcategory = excluded.subcategory,
  lat = excluded.lat,
  lng = excluded.lng,
  town = excluded.town;
